### ISSUE TITLE
macvim url scheme with line number is broken

### ISSUE THREAD

**Issue by rahul342** [macvim-dev/macvim#1020]
**Describe the bug**
mvim url scheme with line number is not working on the latest release (Snapshot 162)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. open a url with line number param (e.g. `mvim://open?url=file://%2FUsers%2Frahulagrawal%2FCode%2Flimebike-web%2Fspec%2Fservices%2Fbike_scan_processor_spec.rb&line=87`)
2. With 162 installed, the file opens but not set to the line number
4. Downgrade to 161 and try the same url, it works correctly this time.

**Expected behavior**
File opens at the passed line number 

**Screenshots**

**Environment (please complete the following information):**
 - Latest snapshot (162)
 - OS: macOS 10.15.1
 - Terminal: iTerm2, browser firefox.

**Additional context**
Potentially related to  https://github.com/macvim-dev/macvim/pull/1002 ?

**Comment by rahul342** [comment]
cc @frarees (Sorry if this is not related to your commit)

**Comment by frarees** [comment]
It is related to #1002 definitively. So I'm not sure if RFC 2396 defines what happens when a query value is a URI itself, if it need to be re-encoded or not. Is there somewhere a statement on this specific scenario?

In your case, not re-encoding (e.g. `mvim://open?url=file:///Users/rahulagrawal/Code/limebike-web/spec/services/bike_scan_processor_spec.rb&line=87`) works on 8.2.319+. 

This is what I do on bash to detect the version. Not bulletproof, enough for my use case:

```
function urlenc
{
	/usr/bin/python -c "import sys, urllib as ul; print ul.quote(sys.argv[1],'/')" "$1"
}

FILE=$1
LINE=$2

MVIMVERSION=`/usr/local/bin/mvim --version | grep 'VIM - Vi IMproved' | cut -d ' ' -f 5`
# not 100% accurate, we could have several patch defs e.g. 1-200, 205-300, 302-500
MVIMPATCH=`/usr/local/bin/mvim --version | grep 'Included patches' | cut -d '-' -f 2`

ENC_FILE=`urlenc "$FILE"`

# pre 8.2.319
#   re-encode, since MacVim mistakenly decodes it
# see https://github.com/macvim-dev/macvim/pull/1002
if [[ $MVIMVERSION < '8.2' || $MVIMVERSION == '8.2' && $MVIMPATCH < '319' ]]; then
	ENC_FILE=`urlenc "$ENC_FILE"`
fi

URI="mvim://open?url=file://$ENC_FILE&line=$LINE"
```

**Comment by ychin** [comment]
Yeah that seems directly responsible for the issue. I’ll take a look tonight. We should add a regression test as well (which a lot of MacVim-specific features don’t have, unfortunately).

**Comment by frarees** [comment]
@rahul342 can you check #1021 see if it works for you?

**Comment by rahul342** [comment]
@frarees Would I need to compile and build your branch to test? What's the quickest way to try your change?

**Comment by ychin** [comment]
Hmm I don’t think this needs additional testing. I tried it and it does work and it’s possible to test locally as well

**Comment by frarees** [comment]
Sorry for the late response. There are build instruction on the wiki. Snapshot 163 will contain the changes, so you could wait for it to be released too.

**Comment by ychin** [comment]
163 was released, so you can just grab the latest build or let MacVim update itself.

**Comment by rahul342** [comment]
@ychin seems like the issue still persists.

**Comment by dx7** [comment]
The issue persists here on snapshot 163.

**Comment by frarees** [comment]
Seems like the changes break compatibility in quite some places, so I'll take time later today to propose a PR reverting the changes, so that everyone gets it back as it was in 161. I can make my use case work by _re-encoding_ (as shown in my comment above, in case anyone else with a similar issue lands here).

Sorry everyone for the inconvenience.

**Comment by ychin** [comment]
Maybe I'm dense but it seems to work for me. @dx7 / @rahul342 can you post the exact URL? Also, if you `%2F` with `/` does it work?

**Comment by dx7** [comment]
Example: `open "mvim://open?url=file://%2Fetc%2Fpasswd&line=10"`.

**Comment by dx7** [comment]
Example: `open "mvim://open?url=file://%2Fetc%2Fpasswd&line=10"`.
Another example is cmd+click url on iTerm2. Both work on snapshot 161.

**Comment by frarees** [comment]
Yeah, changes introduced on 162+ make it so that path in `file://<path>` should not be encoded. 

161 and previous: path *must* be encoded. 
162 and 163: path *must not* be encoded. 

This brings back the original question: 
> So I'm not sure if RFC 2396 defines what happens when a query value is a URI itself, if it need to be re-encoded or not. Is there somewhere a statement on this specific scenario?

Does anyone know how to best comply the standard?

Either way, in order to bring compatibility back, we should _at least_ make it so that it parses encoded paths, as it was. So:

Proposed 164: path *could* be encoded or not.

This should address backwards compatibility, and allow users to also do `open "mvim://open?url=file:///etc/passwd&line=10"`

**Comment by dx7** [comment]
That really works without url encoded.

I think that proposed 164 is the best way for now since other apps need time to adapt.

**Comment by frarees** [comment]
I sent a PR to bring back pre 162 behaviour. Can you verify it works for you?

**Comment by ychin** [comment]
Let me try this out later but is this going to break the white space issue again? If so we should try another solution? I will write a regression test later for catch all the cases we want

**Comment by frarees** [comment]
> Let me try this out later but is this going to break the white space issue again?

It will break as long as the contents of `url` are not encoded (not sure if the whole `url` or the path without `file://`). 

> I will write a regression test later for catch all the cases we want.

Great, that would help ensure we get it right for everyone.

**Comment by dx7** [comment]
@frarees PR #1040 works like 161 on line number issue.

**Comment by ychin** [comment]
I rejected #1040 because that simply moves the behavior back to 161 which doesn't work for cases like file names with space, which seems like a bad trade to me.

Thinking more about it, the issue here is that in your URL, the slashes are escaped to `%2f`. Furthermore, the first two slashes didn't get escaped, but the slashes afterwards are. If you paste your URL (file://%2FUsers%2Frahulagrawal%2FCode%2Flimebike-web%2Fspec%2Fservices%2Fbike_scan_processor_spec.rb) to Safari (or Chrome) in macOS you will notice that it doesn't work. I think it was an accident that this was allowed, and to fix this you simply need to use unescaped slash (`/`) characters. [This page](https://stackoverflow.com/questions/2322764/what-characters-must-be-escaped-in-an-http-query-string) also describes how it's perfectly valid to have the slash character in the query of the URL.

@rahul342 / @dx7 Are you using any tools or scripts that generate those URLs? We could manually add some code that unescapes `%2f` specifically but I'm reluctant to do that, especially since for those URLs if you just paste to a browser they would not work as they are not valid URLs.

**Comment by ychin** [comment]
Also note that if you do `:help mvim://` the examples do not escape anything:

```
10. mvim:// URL handler				*mvim://* *macvim-url-handler*

MacVim supports a custom URL handler for "mvim://" URLs. The handler is
supposed to be compatible to TextMate's URL scheme as documented at >
	http://blog.macromates.com/2007/the-textmate-url-scheme/.

Currently, this means that the format is >
	mvim://open?<arguments>
where "arguments" can be:
	* url — the actual file to open (i.e. a file://... URL), if you leave
		out this argument, the frontmost document is implied
	* line — line number to go to (one based)
	* column — column number to go to (one based)

For example, the link >
	mvim://open?url=file:///etc/profile&line=20
will open the file /etc/profile on line 20 when clicked in a web browser.

Note that url has to be a file:// url pointing to an existing local file.
```

**Comment by rahul342** [comment]
@ychin that's what iterm2 generates when cmd+clicking a file path with line number.

**Comment by rahul342** [comment]
We can may be open an issue there, but both of these are popular tools, hopefully we can make them work together.

**Comment by ychin** [comment]
Can you be more precise? I have iTerm but I don't use it much so I'm not sure what the exact meaning of "file path with line number". Are you talking about for example make / build outputs?

**Comment by ychin** [comment]
In particular I'm curious if this is a specific MacVim integration (that you had to select) or just some generic way iTerm handling of file URLs.

**Comment by ychin** [comment]
Is it this? https://stackoverflow.com/questions/38906815/can-i-click-on-a-filename-and-line-number-in-iterm2-to-open-that-file-in-visual

I may have to take a look.

**Comment by dx7** [comment]
@ychin I use iterm2 cmd+click to open an url (file path or web link) with default app. like that overflow question you linked here. my code files open on macvim. maybe it's an inconsistent behavior on the iterm2 side since url works without line number.

maybe macvim could unescape `2%f` as a deprecated behavior to be removed in a near future. just to give time to other apps to adapt their integration. I can open a new issue on iterm to notify that deprecated unescape.

**Comment by matthewd** [comment]
To me, it seems pretty demonstrable that the encoded form must be valid (and should probably be preferred by `mvim:`-URL-generating tools):

```sh
mkdir /tmp/x
touch '/tmp/x%2fz'
touch '/tmp/x/z'
touch '/tmp/x&line=5'
touch '/tmp/x%26line=5'
```

Using the encoded form, those four files can be referenced as:
```
mvim://open?url=%2Ftmp%2Fx%252fz
mvim://open?url=%2Ftmp%2Fx%2Fz
mvim://open?url=%2Ftmp%2Fx%26line%3D5
mvim://open?url=%2Ftmp%2Fx%2526line%3D5
```

Without encoding, I believe they're unavoidably ambiguous.

Now, that's not to say that the unencoded form shouldn't also work -- just like in all other URLs, if the value part contains an unencoded character _that doesn't have special significance in that location_ (here, most characters other than `&`, `%`, and `#`), that character has its literal meaning, just as the encoded version does.

RFC3986 speaks to this:

> The characters slash ("/") and question mark ("?") may represent data within the query component. 
> [..] as query components are often used to carry identifying information in the form of "key=value" pairs and one frequently used value is a reference to another URI, it is sometimes better for usability to avoid percent-encoding those characters.

ISTM that while the help example is following the above "don't needlessly encode slashes here" advice, that doesn't change the fact it is fundamentally still a URI-encoded value.

#1040 is correct, and who- or whatever was generating a URL containing a literal space is the thing that needs to be corrected. (Again, because they'd presumably do the same if the path contained a literal `&line=5` -- and surely we can agree _that_ would be wrong.)

I don't have Textmate installed, but I'd strongly expect it to also behave as above [that is, the same way `mvim://` has worked for the last 12 years]. But either way, as the documentation _starts_ by describing the format as compatible, it might be worth checking.

**Comment by ychin** [comment]
@matthewd I think you made a mistake in your example, and that mistake is why I'm resistant to allowing escaped slashes.

The proper file protocol URL for `/tmp/%2fz` is `file:///tmp/%252fz` (You can try this with your own web browser). For `/tmp/x&line=5` the URL should be `file:///tmp/x%26line=5`. Note that slashes are *not* encoded (because they represent the separator) but the "%" is. In your example you encoded both the slash and "%", which would lead to confusion when you are trying to understand what that path actually means (it would imply the `/` is actually a file name rather than path separator).

If you want to encode the whole path, it should be `file:%2F%2F%2Ftmp/%25252fz`. It's quite verbose and in my opinion unnecessary. Ultimately we can encode as many times as we want if we agree to decode the same amount of times, but the point I'm making is that it's unnecessary to do so, and in any case you need to make sure the "%"/"&" (or space in the original issue) is encoded 1 more time than the slashes. There is no real confusion if we leave the `file:///` unencoded because they are already in the query component of the URL.

So the correct URL that I think we should use in your examples are:
* `/tmp/x%2fz` -> `mvim://open?url=file:///tmp/x%252fz`
* `/tmp/x/z` -> `mvim://open?url=file:///tmp/x/z`
* `/tmp/x&line=5` -> `mvim://open?url=file:///tmp/x%26line=5`
* `/tmp/x%26line=5` -> `mvim://open?url=file:///tmp/x%2526line=5`

If we encode the slashes they would become the verbose form of:
* `/tmp/x%2fz` -> `mvim://open?url=file:%2F%2F%2Ftmp%2Fx%25252fz`
* `/tmp/x/z` -> `mvim://open?url=file:%2F%2F%2Ftmp%2Fx%2Fz`
* `/tmp/x&line=5` -> `mvim://open?url=file:%2F%2F%2Ftmp%2Fx%2526line=5`
* `/tmp/x%26line=5` -> `mvim://open?url=file:%2F%2F%2Ftmp%2Fx%252526line=5`

**Comment by ychin** [comment]
I made a workaround that should fix this. Will be out next releease.

**Comment by matthewd** [comment]
> The proper file protocol URL for `/tmp/%2fz` is `file:///tmp/%252fz` (You can try this with your own web browser). For `/tmp/x&line=5` the URL should be `file:///tmp/x%26line=5`. 

Agreed. But if you copy that `file://` URL and paste it into the GitHub search box at the top of this page, and then look at the resulting URL, you will find that the way you pass it inside a querystring value, according to your browser, is to encode it again. And that's what we're doing here: the `mvim:` bit isn't a static string prefix, but a nested URL. Assuming your browser encodes as aggressively as mine, you'll also find that you can manually replace the `:`, `/`, and `=`, and the server will interpret the value the same way, because those are defined as being interchangeable in that position.

So, while I agree that it is unnecessary to encode the slashes because they never have significance after a `?`, I maintain that it is equally valid for _one_ level of `/` -> `%2F` transformation to have been applied -- because the value we're talking about is an encoding _of_ the `file:` URL, not an encoding _within_ the `file:` URL. 

All of `mvim://open?url=file:///tmp/x%2526line=5`, `mvim://open?url=file:%2F%2F%2Ftmp%2Fx%2526line=5`, and `mvim://open?url=%66%69%6c%65%3a%2f%2f%2f%74%6d%70%2f%78%25%32%36%6c%69%6e%65%3d%35` contain exactly the same `url` value (`file:///tmp/x%26line=5`, which we agree represents the file `/tmp/x&line=5`), and a piece of software generating any of them is behaving correctly.

Your suggested `mvim://open?url=file:///tmp/x%26line=5` does not: [any URL parser](https://www.freeformatter.com/url-parser-query-string-splitter.html) will state that that contains a `url` value of `file:///tmp/x&line=5`. We can get away with that one, because although it's not the `file:` URL we agree it should be, there's no other reasonable interpretation of that character in that position -- though it'd be a different story if the `&` was a `?`. But in your last example, being insufficiently-encoded is a clear problem: `mvim://open?url=file:///tmp/x%2526line=5` contains a `url` of `file:///tmp/x%26line=5`, which per above, you agree refers to `/tmp/x&line=5`, not `/tmp/x%26line=5`.

I appreciate a partial workaround, but I'm still extremely confident that #1002 was wrong in its premise, and there was never a bug to begin with. The URL for `/tmp/foo bar` is `file:///tmp/foo%20bar`, which has an mvim URL of `mvim://open?url=file:///foo%2520bar`, and that has worked just fine for the last 10 years.

**Comment by frarees** [comment]
> I'm still extremely confident that #1002 was wrong in its premise, and there was never a bug to begin with.

That could totally be it. And since it's both breaking compatibility for some users and seems people have been happy for a long time before, I proposed to just go back to how it was (#1040). Either way, it's great that there's a discussion going on how to do this right. 

This is how I made it work with the original implementation (161 and previous):

```
function urlenc
{
	/usr/bin/python -c "import sys, urllib as ul; print ul.quote(sys.argv[1],'/')" "$1"
}

FILE=$1
LINE=$2

ENC_FILE=`urlenc "$FILE"`
ENC_FILE=`urlenc "$ENC_FILE"`
URI="mvim://open?url=file://$ENC_FILE&line=$LINE"
```

As you see, I had to do the encoding twice, otherwise e.g. files with spaces would not work. Encoding twice felt wrong, but maybe I'm missing something?

**Comment by matthewd** [comment]
@frarees does this help it feel any less wrong?

```shell
FILE=$1
LINE=$2

ENC_FILE=`urlenc "$FILE"`
FILE_URL="file://$ENC_FILE"

ENC_URL=`urlenc "$FILE_URL"`

# Obviously unnecessary, because we know what characters are in there, but technically correct, and helpful for symmetry
ENC_LINE=`urlenc "$LINE"`

URI="mvim://open?url=$ENC_URL&line=$ENC_LINE"
```

**Comment by frarees** [comment]
@matthewd it does. It helps understand there's the `file://<encoded contents>` and the `mvim://<encoded contents>`, whereas in my example it feels like there are two encodings cause the program is decoding the same thing twice.

**Comment by ychin** [comment]
@matthewd There are a couple things going on here, but I think we should at least agree that this issue's original URL is not formed properly? It looks like this:

File: `/tmp/file name.txt` -> URL: `file://%2Ftmp%2Ffile%20name.txt`.

Either way the space should be encoded one more time than the slash. Either of the two would work depending on the encoding scheme:

* (No encoding) `file:///tmp/file%20name.txt`
* (Encoding) `file:%2F%2F%2Ftmp/file%2520name.txt` or `file:///tmp/file%2520name.txt`.

> I appreciate a partial workaround, but I'm still extremely confident that #1002 was wrong in its premise, and there was never a bug to begin with. The URL for /tmp/foo bar is file:///tmp/foo%20bar, which has an mvim URL of mvim://open?url=file:///foo%2520bar, and that has worked just fine for the last 10 years.

I kind of agree with you that most URL component parser will decode the query items and then we should theoretically be encoding a space as `%2520` to double-encode it so it decodes properly when being parser. Couple issues I see:

1. MacVim claims to be TextMate compatible, and TextMate doesn't do double decoding, so it expects a space to be `%20`.
2. iTerm2 *also* doesn't do double-encoding, and if you cmd-click on a file name with space, it will just encode it once to `%20`. That could potentially be fixed, but it does lead to an awkward situation where different people running different versions of iTerm2 and MacVim will have different results with their names not being respected. I'm not sure if there is a good solution for this.

On the other hand MacVim has always double-decoded and the recent change did break it. I guess I can see the value of reverting back to the original behavior and just ask iTerm2 to fix it for MacVim integration.

**Comment by matthewd** [comment]
> TextMate doesn't do double decoding, so it expects a space to be %20

Oh!

> iTerm2 also doesn't do double-encoding, and if you cmd-click on a file name with space, it will just encode it once to %20

Oh oh!

Sorry, I definitely should've at least checked the latter. This has worked so reliably for me (both from iTerm and elsewhere) for so long, and I apparently just assumed I'd opened space-containing paths from iTerm along the way. 😔 

Sooo.... my revised proposal is that MacVim should double-decode [and that ideally URL-building applications _should_ double-encode], but that MacVim also accomodate under-encoded values encountered along the way. (I think this is slightly different from #1043, but I could easily be misreading that.)

1. Extract the 'url' value from the `mvim:` URL
2. Decode it as "normal"
3. You now have a `file:` URL with some characters still encoded (properly behaving client), but also possibly with some characters not (e.g. raw space, per your example)
4. Re-encode characters that are not permitted in a URL
5. Parse the result as a URL, to extract the path etc.

I think 3-5 there describes how a web browser behaves, for example: when given `http://www/foo%20bar`, it will request exactly that from the server; when given `http://www/foo bar`, it'll assume you meant the first one, and request the same thing.

In other words, double-encoding is the right thing, and extracting the parameter from the `mvim:` URL will always perform the initial decode -- MacVim just then chooses to be accomodating on the _second_ decode, by not erroring when it sees a non-URL-valid symbol, and instead pretends such a character was in fact encoded.

I'm afraid I got a bit lost trying to figure out how to spell that in ObjC, but I think this does what I have in mind in Swift, if that's close enough to make sense?

```swift
import Foundation

let urlSet = CharacterSet.urlFragmentAllowed
                .union(.urlHostAllowed)
                .union(.urlPasswordAllowed)
                .union(.urlQueryAllowed)
                .union(.urlUserAllowed)
                .union(CharacterSet(charactersIn: "%"))

print("file:///tmp/foo%20bar baz".addingPercentEncoding(withAllowedCharacters: urlSet) ?? "?");
```

In this proposal, `file:///tmp/foo bar baz`, `file:///tmp/foo%20bar baz`, and `file:///tmp/foo%20bar%20baz` are all equivalent, and mean `/tmp/foo bar baz`. Consequently, so do both `mvim://open?url=file:///tmp/foo%20bar%20baz` and `mvim://open?url=file:///tmp/foo%2520bar%2520baz`.

The only way to reference a file literally named `/tmp/foo%20bar` is as `file:///tmp/foo%2520bar`, and thus `mvim://open?url=file:///tmp/foo%252520bar`. This is a breaking change from the pre-#1002 behaviour, where `mvim://open?url=file:///tmp/foo%2520bar` would previously have opened that file, but would now look for `/tmp/foo bar`. But in exchange for breaking previously-working URLs that reference a filename containing a `%` (or `?`/`#`), we fix compatibility with existing clients that under-escape, for all other characters.

And we should then encourage iTerm to adopt double-escaping, because that's the only truly unambiguous way to communicate all possible paths, and is just The Right Thing.

Old/current iTerm single-escaped -> Old MacVim = (old behaviour) spaces break, basic paths work
Old/current iTerm single-escaped -> Proposed MacVim = all paths work unless containing `%`, `?`, `#`
Future iTerm double-escaped -> Old MacVim = all paths work
Future iTerm double-escaped -> Proposed MacVim = all paths work

**Comment by ychin** [comment]
On first glance, this seems ok. It's kind of an ugly compromise that basically works either either method, and with special characters like "%" we need the double-encoding for it to work (I think spaces are the main benefits of it). It's a strictly looser set of allowed input than old MacVim.

I still need to think about this a little. Magic behaviors with ambiguities in APIs can sometimes leads to training users with sloppy expectations (since someone may try it and it works) but there is the benefit of working with existing tools.

**Comment by ychin** [comment]
Sorry for the delay, but I just filed https://github.com/macvim-dev/macvim/pull/1055 which fixes these encoding issues as described above. Basically, it will use double-encoding by default, just like how MacVim used to work before the recent changes, but it will opportunistically support single-encoding as well to make it play nice with iTerm.

**Comment by dx7** [comment]
sounds great. thanks.
