### ISSUE TITLE
MacVim --clean consumes one argument

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#1058]
**Describe the bug**
MacVim (latest master, commit d552421a21b24493ed0745980cf0bb267b021289) consumes an argument and opens 1 less windows than files (or no files when one file supplied)

This doesn't happen in terminal Vim from the same build or when `--clean` is not supplied even with an empty configuration.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Build MacVim in directory `/Users/eirnym/dev/macvim` using `git clean -fdx && make clean && ./configure --enable-python3interp=dynamic && make`
1. Create test files with `cd /Users/eirnym/test && rm -rf *txt && touch {1,2,3}.txt`
1. Open Vim with command `src/MacVim/build/Release/MacVim.app/Contents/MacOS/Vim --clean *txt`
1. When Vim (terminal) opens, execute `:ls` to make sure that all 3 buffers on the list, exit Vim. (it's correct behaviour)
1. Open MacVim with command `src/MacVim/build/Release/MacVim.app/Contents/MacOS/MacVim --clean *txt` (or by listing them exactly)
1. Only 2 windows were opened instead of 3
1. When you specify only _one_ file, no windows will be open

**Expected behavior**
A buffer with first file is opened

**Environment (please complete the following information):**
 - Vim version commit **d552421a21b24493ed0745980cf0bb267b021289** (currently the latest)
 - OS: macOS 10.15.6 (19G60d)
 - Terminal: Terminal.app

**Comment by ychin** [comment]
Seems like this is a longstanding bug. Will need to take a look.

Either way, if you want to launch MacVim with `--clean`, it's probably better to use the bundled `mvim` script or use `src/MacVim/build/Release/MacVim.app/Contents/MacOS/Vim -g --clean *txt`.

**Comment by eirnym** [comment]
Thank you @ychin 

Why `MacVim` binary is not correct version to run? If it's broken somehow why it shouldn't be fixed?

`mvim` script is not useful in this case as I want to run freshly built app without touching installed. I don't need auto discovery for MacVim's location. 

For general use I have my own alias pointing to `/Applications/MacVim.app/Contents/MacOS/Vim -g`

**Comment by eirnym** [comment]
Ps: `Vim -g` indeed works correctly. 

Should we focus on `MacVim` binary here? For me it's a simple wrapper for `Vim` executable so I expect it works the same

**Comment by ychin** [comment]
`MacVim` is the raw binary for the macOS app container and shouldn't need to handle command parsing. It's not the same binary as `Vim`, which is actually the Vim program. In general, the "standard" way to call macOS apps is to use `open`: `open /Applications/MacVim.app`. Otherwise, doing `/Applications/MacVim.app/Contents/MacOS/Vim -g` works.

Alternatively, you can get your familiar `gvim`, `vim`, `view`, etc from `/Applications/MacVim.app/MacVim.app/Contents/bin/`, so you can just call `/Applications/MacVim.app/Contents/bin/gvim` if you want. They all just symlink to `mvim` anyway which is what you probably want to use (whether you freshly install it or not should have no relevance because it works by looking at its own locaiton).
