### ISSUE TITLE
Dot command to repeatedly click the same area more than once

### ISSUE THREAD

**Issue by mmroczka** [macvim-dev/macvim#1097]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
It is difficult to click the same thing more than once when using MacVim. I occasionally am in my calendar, for instance, and I want to adjust the date on an event by a couple of days forward. I'd normally click the big "+add day" button a few times, but with MacVim, I click it once, and then my cursor no longer stays there so it's impossible to click it multiple times without activating the hints multiple times and hitting some 3 key combo multiple times only to click a button twice.

**Describe the solution you'd like**
I actually _like_ the fact that it MacVim restores our cursor's position, but I think in order to combat the rare case when this isn't useful I'd hope for a dot (repeat) command.

**Describe alternatives you've considered**
Alternatively, we could just have a checkbox in settings that disables the cursor being restored. Again, I like this feature so it'd be a bummer to have to turn it off to get the occasional same-button-click thing.

**Additional context**
None that I can think of.

**Comment by ychin** [comment]
Sorry @mmroczka I'm not sure I'm understanding this issue. What do you mean by "my cursor no longer stays there". Also not quite sure are you talking about using a mouse, or keyboard (since you referred to dot command). I'm also not sure what you meant by "cursor being restored". We are talking about the cursor showing where you are typing right?

If you have screenshots/videos with the relevant parts highlighted that would be very useful.

**Comment by mmroczka** [comment]
Uhm, I'm embarrassed to say this, but this was the wrong Github repo to post this too actually. Haha. Closing it now.
