### ISSUE TITLE
Command mappings (<D->) do not work if MacVim was called from Vim

### ISSUE THREAD

**Issue by 097115** [macvim-dev/macvim#1108]
**To Reproduce**
Run the TUI Vim. Launch MacVim with`:!mvim` or by typing `mvim` in `:term`. Mappings with the Command key do not work (like, pressing ⌘-v in Insert mode will result in `<D-v>` being inserted, pressing ⌘-a in normal mode will result in entering insert mode with `:help a` command)

**Expected behavior**
⌘ mappings should work.

**Environment:**
 - Vim version:

    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 11 2020 06:56:08)
    macOS version
    Included patches: 1-1830

 - MacVim version:

    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 21 2020 04:03:24)
    macOS version
    Included patches: 1-1719

**Comment by ychin** [comment]
Hmm, this is an odd issue. Don't think I would have thought people use Vim that way. But I think the issue is the regular Vim would set the `VIMRUNTIME` environmental variable, and then when you use regular Vim to launch `mvim`, MacVim inherits the `VIMRUNTIME` from it, which is why it lost the MacVim-specific functionality.

I'm not sure if I want MacVim to lock the runtime dir because launching Vim with a customizable `VIMRUNTIME` is allowed in regular Vim. I think that does mean launching different types of Vim this way is probably not advised. I think you could just make sure to use TUI MacVim to keep it consistent. Otherwise if you really want to use the regular TUI Vim to launch MacVim, you could call `unset VIMRUNTIME` first.

**Comment by 097115** [comment]
Thanks, @ychin!
