### ISSUE TITLE
What happened to fonts?

### ISSUE THREAD

**Issue by 9mm** [macvim-dev/macvim#1152]
I see in the latest release with the new icon that it has a new renderer, that's awesome! It appears though my entire editor feels uncomfortably different. The line-height is now super large...

I remember this exact thing happened before and a fixed was merged in, heres the issue: https://github.com/macvim-dev/macvim/issues/949

Based on how my editor looks, it appears its the exact same problem to a T (at least visually, anyway), and a fix was merged in before.

**Comment by eirnym** [comment]
@9mm, thank you for an issue

Yes, it's a completely new renderer and the decision was give it a go. The patch for this renderer wouldn't be the same, but could be similar.

As far as I remember you were using modified Anonymous Pro

Could you please share _exact_ version of your font and a source where to find new versions of your modified font to play with. I have no issues for myself with Fira Code, but font has different properties than yours. 

Anonymous Pro I'd also try a new version of unmodified Anonymous Pro. Any font modifications could change any font property because of it's recompilation.

**Comment by 9mm** [comment]
Sure, here it is modified: 

[Anonymice Powerline.ttf.zip](https://github.com/macvim-dev/macvim/files/5740530/Anonymice.Powerline.ttf.zip)

Here's the original font which does the same thing for me, so you could just pretend for the sake of this issue that I'm not using a modified version at all (I just tested it with this original font straight from the source). I also downloaded the latest version (1.002)

https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1_002.zip

**Comment by ychin** [comment]
Huh I remember seeing this issue getting raised when the stateful renderer was under review in @s4y's pull request (https://github.com/macvim-dev/macvim/pull/858), but I think that was fixed. I will need to take a look. So just to be clear, the *only* issue you see if the line height problem, and not other issues, right?

The old renderer code actually explicitly ignored the line height of the font, and I think we may have missed that in the new code, so we should probably re-introduce that behavior, and potentially give an option to respect line height if we want to.

**Comment by 9mm** [comment]
Awesome! Thanks 👍🏼  And yes thats correct, that's the only issue I see so far.

**Comment by ychin** [comment]
Ok this is "fixed". I put quotes around them because the new behavior is going to be the default as I think it's actually the correct behavior. There is now an option though (use the preference pane, under "Appearance") to tell MacVim to not to preserve font line spacing, which is what you want. @9mm

**Comment by 9mm** [comment]
Awesome! dumb question but how do i download this new release? (on releases page it looks like most recent is 8 days)

Thanks! also, if i disable that option its still leaving the new (very fast) renderer, right?

**Comment by ychin** [comment]
The new release is not out yet. Will probably be 1-2 weeks out as I try to get some other in-progress stuff in first. Probably early Jan. If you are on r166, and set your auto-updater to ignore the current release, it should just prompt you the next time a new one comes out.

Yes the fast renderer is going to be in still. This just changes how we initializes the font.
