### ISSUE TITLE
Is there a nightly build?

### ISSUE THREAD

**Issue by kneep** [macvim-dev/macvim#1206]
Or is it possible for us to release more frequently?

**Comment by eirnym** [comment]
I'd like more frequent releases too

**Comment by ychin** [comment]
Hi, sorry but I have been absent for last few months for personal workload reasons, but it's kind of crappy to just leave the software persistently stuck at an old release. I'm trying to catch up to the filed issues that I haven't responded to but I'll try to push a release this week.

As for nightly build, I'm not a big fan of it, because I currently manually sign the build myself (I don't trust the CI system with my private keys), and so I either have to manually sign a build every night, or it has to remain unsigned which isn't the best way to deploy a Mac app. I think I should just get on it and make sure to have a regular release cadence.

**Comment by kneep** [comment]
Hi, @ychin. Great to hear from you. A release in near feature is fantastic. Thank you.

**Comment by fs111** [comment]
@ychin do you have a rough idea when the next build will come out? One of the plugins I am using started failing on MacVim b/c it is so old compared to upstream. It would be great if we could get a newer version. Thanks!

**Comment by ychin** [comment]
I just created a pre-release for snapshot-172 (https://github.com/macvim-dev/macvim/releases/tag/snapshot-172). I will probably release it out tomorrow. I just grabbed the latest from Vim upstream so usually like to wait at least one day to see if there are any upstream issues first.

**Comment by ychin** [comment]
Released now: https://github.com/macvim-dev/macvim/releases/tag/snapshot-172

Closing ticket as I don't intend to publish nightly releases for the signing issues as mentioned above.

**Comment by eirnym** [comment]
Is it possible to make at least monthly releases in the future?

**Comment by ychin** [comment]
Yeah that's usually the plan… :/

I made some additional reminders to make sure to do that even if we don't have MacVim-specific features to catch up to Vim upstream.

**Comment by eirnym** [comment]
It's wonderful news!

**Comment by kneep** [comment]
@ychin Thanks. Just got the update :)
