### ISSUE TITLE
Not showing new window in OS X 10.9

### ISSUE THREAD

**Issue by d-c** [macvim-dev/macvim#1212]
I can run Macvim.app in the current (8.2.3455 (172)) version on my OS X 10.9, but there is no new window with empty file (no matter what setup I use). I can select the recent file, but the new window with text doesn't appear. Drag'n'drop doesn't work either.

Last version I used without issues was a very ancient one. When I try to user a newer version, it breaks even the older one into the same non-working behaviour, so to get back to the working state is not easy. I cleaned up anything I found, what might have any connection to MacVim and tried to use older versions. Ended up with "Custom Version 8.2.539 (163)" released on 12 Apr 2020 which worked again.

When I try to run the native app (/Applications/MacVim.app/Contents/MacOS/MacVim) from the shell, it runs non-graphical vim. After I quit with :q it says:

2021-10-04 12:54:44.989 MacVim[34079:507] -[MMWindow setTitlebarAppearsTransparent:]: unrecognized selector sent to instance 0x7fb5dad3d8e0, but I don't return to shell before I quit the graphical interface.

If I try to select e. g. a file from Recents, it opens in terminal, but with very limited possibilities of work, no graphical window.

**Comment by ychin** [comment]
I can try to run this in a VM. 10.9 is definitely on legacy support so it isn't very well tested. I think this is the transparent titlebar support and I think we just need to add some checks to make sure it doesn't call it on old version of OSX.

> Last version I used without issues was a very ancient one

Do you know what "ancient one" means? a few months / a year / a few years ago?

**Comment by d-c** [comment]
I am sorry, I added those extra pieces into the original post, it might have been missed. So once again:

1.  I did try to manually remove all .vimrc and files found in ~/Library (everything found which had *macvim* in name/directory).
2. IMHO the last version working on OS X 10.9 is 163 released on 12 Apr 2020.

I tried to compile recent git version and it fails on XIB file for preferences compilation. The file is for X Code 8.0 and up, there is only XCode 6.2 on 10.9. I don't really understand UI Designer being mostly just a console guy. :-) Sorry.

**Comment by ychin** [comment]
Is there a reason why you need to build MacVim from scratch? Because we moved from NIB to XIB it could be hard for you to build locally on 10.9

**Comment by d-c** [comment]
No real reason. I just wanted to give it a try, with an opportunity to try a bit of debugging. But it's really of a very little use for me, I usually program in plain C.

**Comment by d-c** [comment]
I tried a new 173 version and I must admit, that the issue is all the same:

2022-08-08 00:21:15.198 MacVim[13815:507] -[MMWindow setTitlebarAppearsTransparent:]: unrecognized selector sent to instance 0x7fb8a1c7d590
8H4C31H

...no new window...

**Comment by ychin** [comment]
Thanks for reminding me about this issue. I'll set up some VMs to test it.

I do wish GitHub Action provides older VMs but I guess generally Apple dislikes maintaining older versions of OSes like this.

**Comment by d-c** [comment]
@ychin IMHO is 10.9 the Apple's top system according to ergonomic use, compatibility with SW (some of which was quite expensive), design and stability. I have used quite a lot of systems (and tough trainings on some of them), so I am not comparing just a few impressions.

I have tried newer OS X and macOS systems. One difficulty for me is screen handling. It might be well readable on a retina screen, but $2k+ profi CGs by EIZO seem unreadable. Other is that newer systems are kind of broken in regard of security (from stupid "business" reasons - e. g. to let unprivileged users buy and run apps from store), which in turn is followed by more and more stupid remedies. And more incompatibilities to Unix rules and existing programs. The last more less usable was High Sierra, but it's unsupported for a long time now, so benefits are low.

Yes, I know I will need to move away with my everyday work from 10.9 pretty soon, probably leaving an off-line working place to do photo, sound and video processing. But I am not sure whether to another Mac. *BSD system seems more convincing to me. But still searching...

**Comment by ychin** [comment]
I see. Ok those are good insights.

> compatibility with SW

Lol tell me about it! Every OS update is a mix of excitement and trepidation for me.

Kind of curious what you mean by incompatibilities to Unix rules though, but maybe we are getting off to a tangent.

**Comment by chdiza** [comment]
@d-c Sorry to butt in here, but I was a staunch advocate of keeping support for Tiger here, back in the day, and thus I sympathize greatly with your desire to keep going with an old and non-crappy version of macOS.

Long story short: depending on your workflow and your needs, you might not even need MacVim at all on 10.9.  Perhaps you can get away with just building an up-to-date console Vim.

Terminal emulators on macOS have improved *immensely* since I starting MacVimming around 2007 when it first appeared.  (Holy crap!  Has it been 15 years of MacVimming?)  So much so that the advantages of using MacVim over a plain console Vim---which were many back in 2007---have dwindled down to almost nothing (for me, anyway).

As it turns out, I'm switching to Linux, where there is no way to reliably map the Cmd key in Vim/gVim (without horrible side effects).  This has forced me to retrain my Vim muscle-memory to use other modifiers besides Cmd, and it really only took about two days before it became natural.  Well, guess what?  The ability to have `:map <D-something>` was really the only reason left for me to use MacVim rather than console Vim.   So on those occasions when I do use macOS, I would have no problem just using console Vim instead of MacVim.

* I don't open files by double-clicking them in the Finder, so I don't need MacVim for that.  (Even if I did open files that way, I could make a wrapper that would start console Vim.)
*  At least two terminal emulators on the Mac now have well-functioning fullscreen modes corresponding to "Non-native", aka., Tiger fullscreen, so I don't need MacVim for that.
* Console Vim now supports truecolor, so MacVim has no colorscheme advantage.
* I don't need to drag-n-drop anything onto MacVim, so I don't miss that when using console Vim.
* Etc.

**Comment by ychin** [comment]
Sure @chdiza no problem I always want to hear what drives people to/away from MacVim. But yes how much value you derive from MacVim depends on whether it's the GUI part, or just the "not sucky terminal emulator" part of MacVim that entices you. To me, it was the "GUI of Vim" part that made me start using MacVim.

MacVim does have the ability to do a lot more system integration, such as fully utilizing the Touch Bar or trackpad. There are also some features in progress (with different degrees of doneness) that are difficult to do on a terminal emulator due to the limits of the process boundary (e.g. overlaid scrollbars, smooth pixel scrolling, proper Option-key handling/mapping that would deprecate `macmeta`).

But feel free to use whatever fits your needs. If there's any reason why you think terminal Vim is actually better than MacVim in terms of functionality though I'm curious to hear about it.

---

But on the topic of supporting old versions of OSes, I hear you. I do want to support older versions as much as we can. Sometimes it could get tricky due to API incompatibility (old APIs go from supported to deprecated to removed), and it's difficult to test them in CI. But as long as there are no forcing functions that would force us to bump that number I don't plan to do so (Sparkle 1 still seems supported for now, but the upgrade to Sparkle 2 would probably one of the few reasons we would have to upgrade, unless we want to ship a separate binary that doesn't come with Sparkle updater).

**Comment by ychin** [comment]
Ok have a PR up which fixes this issue. I tested on a 10.9 VM and seems to work, and you can launch and use MacVim again.

One issue that I found: native full screen doesn't seem to work: the Vim window would not resize properly and not take up the whole screen. Non-native full screen still works just fine though. This honestly feels a little like a niche case to me, and unless there is strong desire expressed here it's unlikely I'll fix that, since even just 10.13 seems to handle the native full screen transition just fine. The full screen API and MacVim's handling of it is a alway kind of convoluted and I would much rather spend my time on fixing other issues.

**Comment by chuchana** [comment]
Great! I actually prefer the non-native full screen mode because I find the native animations annoying and I like using [cmd] + [h] to hide the current program.

**Comment by chdiza** [comment]
Native fullscreen mode, a.k.a., Lion-mode, is an abomination :)

**Comment by chdiza** [comment]
@ychin I don't think there's anything on which console Vim outperforms MacVim.  (I mean, other than startup, but that's just the nature of a GUI.)  MacVim does outperform the most popular other gVim, namely the GTK3 build on linux.  (It's so laggy as to be unusable and I build the GTK2 version instead.)

**Comment by ychin** [comment]
Actually, if you use iTerm2, it supports modifyOtherKeys, which MacVim doesn't support yet (but it will soon). Anyway maybe we should stay on topic lol.
