### ISSUE TITLE
Make MacVim work with macOS Focus preferences

### ISSUE THREAD

**Issue by RhvdG** [macvim-dev/macvim#1245]
Recent macOS versions enable users to define different 'focus' settings (allowing or disallowing notifications), based on location, time, and which application is being used. MacVim is not in the list of applications that can be picked. Given that many hours of work are spent using MacVim, it should be.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/34862159/170694508-c30765fb-6536-400e-9af5-a32ccb128c83.png">

**Comment by RhvdG** [comment]
It's probably because I use the homebrew one. 

<img width="468" alt="image" src="https://user-images.githubusercontent.com/34862159/172860890-4ece73e8-809f-46b2-bbd0-bf52dd1413a1.png">

**Comment by sigzero** [comment]
This is probably related to how homebrew does things and is not a MacVim issue itself.

**Comment by eirnym** [comment]
MacVim sedna notifications?

**Comment by ychin** [comment]
I have the same question as @eirnym . Is there a reason you even want this setting? The reason you are not seeing MacVim on the list is that MacVim doesn't send notifications. I actually thought about getting it to send notifications before but I could not find a single use case that isn't "just because we can".

**Comment by ychin** [comment]
Unless someone give a reason for why we want this, I'm not going to investigate much, and let this auto-close. I don't think MacVim is capable of sending notifications right now. @RhvdG
