### ISSUE TITLE
Update to VIM9

### ISSUE THREAD

**Issue by adudek16** [macvim-dev/macvim#1249]
Can we get an update now that VIM9 and vim9 script is now released?
Or at least appoint another maintainer to help keep this alive. I would hate to see this end up like the previous version that just stopped getting support.

**Comment by dataf3l** [comment]
Hi I came here to ask for the exact same thing, thanks @adudek16 for reporting this.
I share the sentiment of wanting the latest stuff.
I can also help test any beta versions on the mac and offer feedback, I have both intel and m1 macs if it is required.
I'm happy to help in any activities required in order to make this happen, let me know what task I can take so I can try to help out.


also thanks for macvim I think it's awesome

**Comment by sigzero** [comment]
I can here to ask as well.

**Comment by ychin** [comment]
Addressed here https://github.com/macvim-dev/macvim/issues/1235#issuecomment-1170619997

**Comment by Hiddensu** [comment]
Why Releases did not update the version of vim9?

**Comment by sigzero** [comment]
> Why Releases did not update the version of vim9?

He's been busy and is just now getting back to it.  See his comment above yours.

**Comment by adudek16** [comment]
Closing at this is tracked via #1235 as mentioned above
