### ISSUE TITLE
[Vim 9] Wrong version in updates checking dialog

### ISSUE THREAD

**Issue by UncleBill** [macvim-dev/macvim#1253]
### Steps to reproduce

1. Click "Check for updates..." menu.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1141198/180768919-36989fb3-5afa-45db-a570-c4d0f2f5ba81.png">

### Expected behaviour

The dialog should report correct version.

### Version of Vim and architecture

9.0.65, GUI, arm64

### Environment

.

### How MacVim was installed

Downloaded from GitHub

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
I'm not seeing that. Can you try it again? The updater uses an appcast.xml hosted on GitHub pages and I didn't update it *immediate* after pushing the update as I was going through the motion. It also takes time for GitHub to regenerate the page. Point I'm trying to make it you only saw that probably because you were downloading the new release as soon as it came out before the updater was reflected to point to the new version.

**Comment by UncleBill** [comment]
It's gone now. Thanks ❤️ 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1141198/180782113-3833467b-2bba-4192-8152-ab4bdbe3ae39.png">
