### ISSUE TITLE
MacVim won't build on El Capitan

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#1342]
### Steps to reproduce

Try to build MacVim from HEAD on El Cap like always.

### Expected behaviour

I expect it to build, like always.  Instead it bombs out in the GUI phase:
```
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -fobjc-exceptions -o objects/MMBackend.o MacVim/MMBackend.m
In file included from MacVim/gui_macvim.m:16:
In file included from MacVim/MMBackend.h:13:
In file included from ./vim.h:290:
./os_mac.h:304:5: error: unknown type name 'clockid_t'; did you mean 'clock_id_t'?
    clockid_t clockid,
    ^~~~~~~~~
    clock_id_t
/usr/include/mach/clock_types.h:53:13: note: 'clock_id_t' declared here
typedef int     clock_id_t;                     /* clock identification type */
                ^
1 error generated.
make[1]: *** [objects/gui_macvim.o] Error 1
```

### Version of Vim and architecture

HEAD

### Environment

MacOS El Capitan

### How MacVim was installed

clone the repo

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
@chdiza I will need to test this in a VM to see, but have you been doing this for a while with no issue? Or have you not built from head in a while and notices that it broke recently?

While we have been making sure MacVim is binary compatible down to 10.9, it's sometimes a little hard to maintain or test code building compatibility (especially because I don't control upstream Vim or Sparkle), and I have been trying to figure exactly what the lowest OS that we can still build on. So if you know if there was a recent breakage or not that would be useful for me.

Also, do you build lower than El Capitan (10.11)? I've been trying to decide what to do with the 10.9 - 10.12 OS comaptibility.

**Comment by chdiza** [comment]
> but have you been doing this for a while with no issue?

I'd been doing it regularly between when El Cap first came out and about a 1.5 years ago, and since then I do it every few months or so.  I note that there was some clock/timer stuff having to do with Apple machines a while back in mainline Vim.

> Also, do you build lower than El Capitan (10.11)?

Not in a long time, no.  My two cents: for 10.9-10.12, just disable building Sparkle.  (That is, make the `configure` script skip Sparkle on those OSes.)   Sparkle is a 3rd-party, unnecessary extra and if anyone on such an old OS still needs MacVim, I'm sure they'd be happy to abandon Sparkle rather than buy a new machine or sit on some version of MacVim.

**Comment by ychin** [comment]
Sure, just disabling Sparkle is easy. That part isn't really an issue. It's more that we don't have regular regression tests to catch potential issues.

**Comment by ychin** [comment]
Can you also tell me what Xcode version you are using to be exact?

**Comment by chdiza** [comment]
> It's more that we don't have regular regression tests to catch potential issues.

I think that's OK.  People who are nerdy enough to be using Vim in the first place, and to have some special need for an older macOS,  have the ability to report build failures here when they arise.

> Can you also tell me what Xcode version (major and minor version) you are using to be exact?

Whichever one is the newest that's compatible with El Capitan.  I don't recall the numbers, sorry.  I'm away from the El Cap machine.

**Comment by chdiza** [comment]
I forgot to mention something important.  While MacVim won't build, upstream regular Vim builds just fine.

**Comment by ychin** [comment]
@chdiza I just made PR #1372 to fix the build issues with El Capitan (10.11). I tested this with OSX 10.11.6 / Xcode 8.2.1 (which is the latest Xcode you can run on this version of macOS).

It builds correctly and works properly, but there are some caveats. Since Xcode 8 wants to build against the 10.12 SDK, you need to manually tell it to use the 10.11 SDK instead. Also, MacVim uses Sparkle 2 by default now, so you need to do some extra steps to make sure to strip the Sparkle dependency so that you won't fail to build or fail to launch the app (Sparkle 2 is only for 10.13+). I updated the wiki (https://github.com/macvim-dev/macvim/wiki/Building#legacy-builds-macos-109---1012) to be a little clearer but basically you need to do the following:

    MACOS_DEPLOYMENT_TARGET=10.11 ./configure --disable-sparkle
    MACOS_DEPLOYMENT_TARGET=10.11 make -j2
    rm -rf src/MacVim/build/Release/MacVim.app/Contents/Frameworks/Sparkle.framework

After that you should be able to run the app. I may later make the last step (removing Sparkle.framework) automatic if you configured with `--disable-sparkle` earlier, but right now this should work if you do it manually.

Also, currently I don't think I can find any CI that has a 10.11 or 10.12 VM image pre-configured, so just let me know if this doesn't work (or if it breaks in the future) and this will need to be looked at on a case by case basis as we won't have CI coverage.

**Comment by ychin** [comment]
Actually, #1373 will handle the auto-deletion of the Sparkle.framework so you won't have to manually delete it. You just have to configure with `--disable-sparkle` and then make and it should just work.

**Comment by chdiza** [comment]
Thanks, I'll try this out next time I'm on the El Cap machine.
