### ISSUE TITLE
a fullscreen :terminal window closes MacVim

### ISSUE THREAD

**Issue by ir0nh34d** [macvim-dev/macvim#1389]
Steps to reproduce:

1. In MacVim, create a :term window
2. Switch it be the only window (via CTRL-W o)
3. Close the :term window by typing "exit"
4. MacVim will close / quit

**Comment by ychin** [comment]
I'm confused. What's the bug? Closing the last window in Vim will close Vim. This is true for any kinds of buffer as well. If you `:q` on the last file opened it will close Vim as well.

**Comment by ychin** [comment]
If you are coming from Neovim, the terminal behavior works a little differently. In Vim, terminals behave just like a regular buffer, which is why closing it will not leave a dummy window around. You could try using `:term ++noclose` which will tell the terminal to avoid closing itself when it exists.

**Comment by ir0nh34d** [comment]
I would agree, however, if you open in :term in a window without making it the only window (i.e. skip step 2 above) then the window closes and MacVim stays open, so it seems inconsistent. 

Here's an additional scenario:

1.  :e ~/.vimrc
2. :term
3. :buffers which outputs:
  1 %a ".vimrc" line 0
  2   aR "!/bin/zsh [running]" line 0
4. Ctrl-W o in the :term window
5. Ctrl-W N to switch to Normal mode
6. :buffers provides the following output:
 1 # ".vimrc" line 0
 2 %aR "!/bin/zsh [Terminal]" line 1
7. Hit "i" to go back to insert mode
8. Type "exit" in the terminal window
9.  MacVim quits, even though ~/.vimrc was open as a buffer

It seems as though only the :term window should close, like it does if it is not the only window.
1. 

1.

**Comment by ychin** [comment]
Buffers do not matter for determining whether Vim (or MacVim) will quit. It's only opened windows. Since your .vimrc file is now not shown, it's not going to play into the logic of whether Vim quits or not.

Only way the .vimrc would matter is if you have `:set hidden` set (in your case, you don't have that set, so .vimrc was actually already unloaded even though it's in the buffer list), *and* you have local changes. Vim will warn you since you have unsaved changes in that case. Otherwise it's just going to quit.

There is no logic in Vim that says "don't close if there are other buffers". For example, the docs for [`:q`](https://macvim.org/docs/editing.txt.html#%3Aq) is as follows (note that it talks about windows, not buffers):

> … Quit Vim if this is the last [edit-window](https://macvim.org/docs/windows.txt.html#edit-window)[.](https://macvim.org/docs/repeat.txt.html#.) …

**Comment by ychin** [comment]
> I would agree, however, if you open in :term in a window without making it the only window (i.e. skip step 2 above) then the window closes and MacVim stays open, so it seems inconsistent.

MacVim stays open because the terminal window wasn't the last one. Just trying to understand why you think that's consistent. Vim exits itself when the last window is closed. If you have two windows and close one, the other one is still open and therefore Vim doesn't exit. I'm not 100% sure what behavior you think Vim should have instead.

**Comment by ir0nh34d** [comment]
Thank you for the detailed clarification.  I was mixing the concepts of the buffers and windows - I had thought that as long as there was an additional buffer Vim would stay open.
