### ISSUE TITLE
Override system locale

### ISSUE THREAD

**Issue by gbergling** [macvim-dev/macvim#1460]
It would be nice to have a setting to override the system local MacVim is using. For example, I work on a macOS Ventura with a German system locale, but prefer to use ViM in general in English language.

I haven't found a ways, to setup MacVim to start in English locale.

**Comment by ychin** [comment]
Are you talking about the menus like "About MacVim" and stuff like that?? Or the localized messages within Vim like the intro screen and `:version` output?

**Comment by gbergling** [comment]
I mean the localized messages within ViM, welcome screen, help and so on. The menu of MacVim itself is partial localized to German, wish could also be configurable, but I would like to have ViM itself use English localization.

**Comment by eirnym** [comment]
to set Vim language to English, put the line on top of your vimrc: `language en_US.UTF-8`

**Comment by gbergling** [comment]
@eirnym Thanks that worked perfectly.

**Comment by ychin** [comment]
@gbergling Just out of curiosity, why do you prefer to use Vim in US English localization, but have you system locale configured to use German? I'm asking to try to understand how people use MacVim. I would like to get MacVim fully localized (so basically get custom MacVim texts translated to German etc) instead of the current "mostly localized" state, but curious why you prefer to use the default US English locale instead.

> The menu of MacVim itself is partial localized to German, wish could also be configurable,

Add this to your vimrc as well: `set langmenu=none`

**Comment by gbergling** [comment]
@ychin I am German an prefer macOS in my native language, regarding the GUI stuff, but on the command line I prefer the English locale, error messages, manual pages and such like. I use ViM for several years now, and having it localized to German language feels somewhat strange. But thangs for the vimrc additions, ViM is no localized the way I have used it before.
