### ISSUE TITLE
Mac OS 10.6 build error: ibtool could not strip "Preferences.nib" because it is not a valid Interface Builder document

### ISSUE THREAD

**Issue by dliessi** [macvim-dev/macvim#204]
Trying to build MacVim snapshot 89 with MacPorts, I get the following error:
```
StripNIB English.lproj/Preferences.nib
    cd /Volumes/MacPorts/build/_Users_davide_ports-substitution_editors_MacVim/MacVim/work/macvim-snapshot-89/src/MacVim
    /Developer/usr/bin/ibtool --strip /Volumes/MacPorts/build/_Users_davide_ports-substitution_editors_MacVim/MacVim/work/macvim-snapshot-89/src/MacVim/build/Release/MacVim.app/Contents/Resources/English.lproj/Preferences.nib --output-format human-readable-text /Volumes/MacPorts/build/_Users_davide_ports-substitution_editors_MacVim/MacVim/work/macvim-snapshot-89/src/MacVim/English.lproj/Preferences.nib

/* com.apple.ibtool.errors */:
/Volumes/MacPorts/build/_Users_davide_ports-substitution_editors_MacVim/MacVim/work/macvim-snapshot-89/src/MacVim/English.lproj/Preferences.nib: error: ibtool could not strip "Preferences.nib" because it is not a valid Interface Builder document.
ibtool could not strip "Preferences.nib" because it is not a valid Interface Builder document.

[...]

** BUILD FAILED **


The following build commands failed:
MacVim:
    StripNIB /Volumes/MacPorts/build/_Users_davide_ports-substitution_editors_MacVim/MacVim/work/macvim-snapshot-89/src/MacVim/English.lproj/Preferences.nib
(1 failure)
```

Snapshot 77 used to build without errors on 10.6 with MacPorts; snapshots 85 to 88 had errors regarding QuickLookStephen (see [the relevant ticket in MacPorts tracker](https://trac.macports.org/ticket/50124)) that are now gone, thanks to 0892c04abaa13823337367eca686e49a05aab568.

**Comment by splhack** [comment]
I'll remove 10.6 support if @rhendric or anyone don't fix the issue.

**Comment by rhendric** [comment]
Looking at it now.

**Comment by rhendric** [comment]
@dliessi, I can't reproduce this error from a fresh checkout of either master or snapshot-89. I don't use MacPorts; is that environment possibly influencing this? Can you build MacVim outside of MacPorts?

**Comment by dliessi** [comment]
With latest master branch, this is the output of ibtool on the three .nib files on my system (10.6.8, Xcode 3.2.6):
```
$ /Developer/usr/bin/ibtool --strip MainMenu.nib --output-format human-readable-text MainMenu.nib
$ /Developer/usr/bin/ibtool --strip FindAndReplace.nib --output-format human-readable-text FindAndReplace.nib
$ /Developer/usr/bin/ibtool --strip Preferences.nib --output-format human-readable-text Preferences.nib
/* com.apple.ibtool.errors */
Preferences.nib: error: ibtool could not strip "Preferences.nib" because it is not a valid Interface Builder document.
```

Opening FindAndReplace.nib and MainMenu.nib with Interface Builder works correctly, while opening Preferences.nib gives this error: `Interface Builder was unable to determine the type of "Preferences.nib".`

Before commit 1497587763d3279073d7c54614fa700b3d736d1f also Preferences.nib opened fine in Interface Builder and was processed correctly by ibtool.
Probably that commit introduced something incompatible with Xcode 3.2.6 (which is the latest version freely available for 10.6).

**Comment by splhack** [comment]
Xcode 4.2 is the last version for OS X 10.6, IIRC.

**Comment by dliessi** [comment]
Yes, but you need a payed developer account in order to get it on 10.6.
MacPorts expects Xcode 3.2.6 on 10.6 because of that.

**Comment by rhendric** [comment]
@dliessi, can you test rhendric/macvim@0fa9a53?

**Comment by splhack** [comment]
@rhendric It includes `s/atsuiButtonClicked/coreTextButtonClicked/` changes?

**Comment by dliessi** [comment]
@rhendric both Interface Builder and ibtool open/process the file without errors.
Do I need to check anything inside the file?

**Comment by rhendric** [comment]
@splhack Nope! Even my Xcode 4.2 can't open master's Preferences.nib, so I was hoping if it worked for dliessi that you would do to it what I did to the older one—just change the Document Versioning setting to target Interface Builder 3.2 format.

Oddly enough, however, I did test my build (with `atsuiButtonClicked`, apparently, which should be broken because it says `coreTextButtonClicked` in `MMAppController.m`) against master build (with `coreTextButtonClicked`, presumably) and noticed the same behavior in both—changing the CoreText setting doesn't take effect until the next window is opened, but then it does, and it's persisted across restarts. I have zero experience in working with GUIs in Xcode, but might it be possible that that event handler isn't actually doing anything useful?

**Comment by splhack** [comment]
@rhendric `MMRenderer` value was actually changed in the defaults with your change, but `coreTextButtonClicked:` method wasn't called any more. I think it is the time to drop old Xcode support if you can't modify Preferences.nib properly. Still you might be able to release MacVim binary for OS X 10.6 users with Xcode 7.2.

**Comment by rhendric** [comment]
Does your Xcode version not have these settings?
![Document Versioning settings](https://cloud.githubusercontent.com/assets/1570964/12272235/4ad9f6b2-b92d-11e5-9c50-012f30070da3.png)
Or is there some cost I'm not aware of to using them?

If neither of the above are true, I don't understand why such a small thing as changing a document setting would push you to drop support.

(I'd submit my own changed Preferences.nib, except I'd be worried about missing other changes that you made, or not dragging the right thing onto the other thing, because again, zero experience.)

**Comment by splhack** [comment]
@rhendric It seems Xcode 7.2 only supports back to Xcode 5.1 for nib file. And I think you should have Xcode 7.2 and Xcode 3.2.6 if you really want to support OS X 10.6 in this repository. I can tell you the changes when I change nib file. In this case, `s/atsuiButtonClicked/coreTextButtonClicked/`.

**Comment by rhendric** [comment]
Fair enough. PR inbound.

**Comment by barracuda156** [comment]
@ychin Thank you for responding! I did not actually hope someone will be willing to help me with fixing MacVim for 10.6, I just got an error with another app which looked identical.

However, regarding MacVim, which is a more interesting matter: do you know if it can work to use a modern `vim` code with a significantly older MacVim to get a native GUI working? I would love to have it on powerpc, but fixing the current codebase for it is probably too involving.

**Comment by ychin** [comment]
> However, regarding MacVim, which is a more interesting matter: do you know if it can work to use a modern vim code with a significantly older MacVim to get a native GUI working? I would love to have it on powerpc, but fixing the current codebase for it is probably too involving.

Not easily. MacVim contains downstream changes so it would include finding a version of MacVim that supports macOS 10.6, and then merging the latest changes from upstream Vim (see https://github.com/macvim-dev/macvim/wiki/Merging-from-upstream-Vim), which would include years of backlogged commits since MacVim hasn't supported 10.6 for a while now (MacVim had already been targeting macOS 10.8+ when I joined as maintainer in 2018). Someone could do it but I'm not going to spend my own time on this. There are enough cross-coupled changes in MacVim that means it will likely have a decent amount of merge conflicts.

**Comment by ychin** [comment]
Just out of curiosity, do you actively use a PowerPC Mac? Or is this more a preservation / tinkering project?
