### ISSUE TITLE
Full Screen white line at top

### ISSUE THREAD

**Issue by dathinaios** [macvim-dev/macvim#250]
When using full screen mode there is a white line at the top of the window:

![white_line_bug](https://cloud.githubusercontent.com/assets/481589/13334075/fb3cdb86-dc01-11e5-97e2-191e798fab31.png)

**Comment by jpetrie** [comment]
MacVim's custom full screen or the native OS X fullscreen? (The toggle is in MacVim's preferences if you're unsure.)

**Comment by dathinaios** [comment]
On the native one

**Comment by jpetrie** [comment]
I can't reproduce this on latest; does it still happen for you? Does it still happen if you upgrade? What version of MacVim are you using?

**Comment by dathinaios** [comment]
> I can't reproduce this on latest; does it still happen for you? 

Yes but only when I start with split screen mode. To reproduce:

1. Press and hold the green button of the MacVim window
2. Select another app window ( I tried it with a finder one)

> Does it still happen if you upgrade? What version of MacVim are you using?

I clicked 'Check for updates' and I am on the latest.

**Comment by jpetrie** [comment]
Okay, I can reproduce it. It has to do with the fake tab line separator MacVim draws since it doesn't use the appropriate window style. There's at least two (I found one, I can't find the other) places where based on whether or not MacVim thinks the separator should be drawn it will shrink the content size by one.

It does this based on some state that is set when fullscreen mode is toggled, most of this state expects to be set up when `toggleFullscreen` happens. It *doesn't* happen when you enter split screen, so that's why it's getting confused.

**Comment by jpetrie** [comment]
@dathinaios If you can, it would help if you could pull down #307 and confirm that it fixes it for you (it does for me).
