### ISSUE TITLE
Incompatible with BufExplorer plugin

### ISSUE THREAD

**Issue by waruqi** [macvim-dev/macvim#258]
hi！

I Found some compatibility issues  after upgrading MacVim.

But the old version (b4winckler/macvim) has no problem.

Select file:

    Escaped
    Error detected while processing function <SNR>18_BESelectBuffer[20]..WinManagerFileEdit[71]..<SNR>43_RefreshWinManager[64]..BufExplorer_ReSize:
    line   15:
    E15: Invalid expression: $
    Error detected while processing function <SNR>18_BESelectBuffer[20]..WinManagerFileEdit[71]..<SNR>43_RefreshWinManager[142]..<SNR>43_ResizeAllExplorers[11]
    ..BufExplorer_ReSize:
    line   15:
    E15: Invalid expression: $

Open new window:

    Error detected while processing function <SNR>43_ToggleWindowsManager[4]..<SNR>43_StartWindowsManager[156]..BufExplorer_ReSize:
    line   15:
    E15: Invalid expression: $
    Press ENTER or type command to continue

My BufExplorer plugin version: 7.2.8

Thanks!

**Comment by splhack** [comment]
Why don't you use the latest BufExplorer?

**Comment by jpetrie** [comment]
`BufExplorer_ReSize`:15 in version 7.2.8 is attempting to do `exe $`. `execute` takes a _string_, and `$` isn't one. My guess is that vim used to accept this due a bug and it's since been patched (although vim's version history is difficult to easily scan, so I gave up looking for the specific change after a few minutes).

Later version of BufExplorer use `normal! $` instead of `exe $` (starting [here](https://github.com/jlanzarotta/bufexplorer/commit/72d86bfae7c99448d793ee2f3bab906a02b5b9dc)).

This isn't a MacVim bug. I think you're just going to have to update your version of BufExplorer.

**Comment by waruqi** [comment]
ok, thanks! :)
