### ISSUE TITLE
Disable Auto-Update

### ISSUE THREAD

**Issue by bmulholland** [macvim-dev/macvim#262]
I have installed MacVim via brew. When the autoupdate feature came out, I accidentally enabled it. Now I keep getting prompted to upgrade to a new MacVim version through a different channel than I usually do. How can I disable the auto-update feature?

**Comment by adamcw** [comment]
I would also like to know how to avoid this feature. Updating via the auto-updater rather than through Homebrew broke my MacVim installation (I believe it was an issue with the YouCompleteMe plugin), I assume it had to do with the version of Python linked. I had to uninstall and reinstall r100 to get it to work again. Updating to r101 today through Homebrew, rather than the auto-updater, has worked just fine. Hopefully this is a fairly isolated incident.

**Comment by chdiza** [comment]
`defaults write org.vim.MacVim  SUEnableAutomaticChecks -bool false`

**Comment by chdiza** [comment]
Probably this should go in the FAQ.

**Comment by splhack** [comment]
done https://github.com/macvim-dev/macvim/wiki/FAQ

**Comment by bmulholland** [comment]
Thank you!
