### ISSUE TITLE
when open new buffer and show tab bar, the screen blacked!

### ISSUE THREAD

**Issue by SolaWing** [macvim-dev/macvim#269]
As the gif shows, when open a new buffer in a new tab, the screen flicker with black.

version is OS X 10.11,  MacVim 101 release.

![bug1](https://cloud.githubusercontent.com/assets/3897953/14807523/e14ce698-0baf-11e6-9480-cd62efa94d87.gif)

**Comment by jpetrie** [comment]
I cannot reproduce this on latest; what version of MacVim are you using and does it still happen if you use the latest screenshot? Does it still happen if you run without your `.vimrc` or plugins loaded?

**Comment by SolaWing** [comment]
Indeed it is ok when no plugin load. After further test, I've found the FileType autocmd cause this issue. I profile functions and found: My plugin Tagbar runs 200ms when switch to new file.

so now I can reproduce this issue without .vimrc or plugins loaded, just do the following cmd:

```
filetype on
autocmd FileType * sleep 20ms   " the longer the issue more obvious
take path/to/file
```

**Comment by jpetrie** [comment]
I don't think there's anything we can do about this.

MacVim has to wait for vim to tell it how to draw a given buffer. Vim may need to process autocommands and file type plugins in order to do that, so MacVim can't draw until those are completed. If your autocommands take too long, you will see visual artifacts and delays because MacVim has to simply wait for the information to come in.
