### ISSUE TITLE
Insta-fullscreen.

### ISSUE THREAD

**Issue by jordwalke** [macvim-dev/macvim#289]
One thing I miss about the terminal (iTerm) is the ability to instantly full screen. This would be great to reduce the animation time for MacVim to nearly zero (I'm referring to the custom full screen feature already implemented).

**Comment by chdiza** [comment]
If you mean the "non-native" mode, around since Tiger, here is how I do it.  You have to edit the source and build your own.

Open up src/macvim/mmfullscreenwindow.m.  There are four places where the number ".25" occurs.  That governs the irritation level (i.e., animation delay).  I just replace it with ".00" and build.  Entering and exiting fullscreen will be nigh instantaneous.

It isn't perfect.  There's a little bit of a blinking illusion, particularly with dark colorschemes.

Maybe you can try ".1" or something like that.

**Comment by jordwalke** [comment]
Thanks! Maybe this should be the default for "non-native" mode. There are two kinds of people in the world - those that can spare > `16ms` when full screening their apps and those that can't. Those that can, can use the native OS full screen animation! :D

**Comment by chdiza** [comment]
I found it so easy to make my local changes that I didn't bother asking for it to be the default.  I learned this trick *years* ago.  (Maybe 2008? Not long after MacVim gained fullscreen mode.)

Maybe it would be more convenient if it was settable using a hidden pref (`defaults write -app MacVim MMWasteMyTime -bool false`).  But that might be a lot of work to change the code.  I myself am content to just keep a local branch into which I merge master.

There are tons of non-animation-related reasons why people might prefer non-native mode (I find it superior to native mode in every respect), and I wouldn't want to force them to accept no-animation as the default.  (Well, I *would*, but to my everlasting disbelief, people like having their workflows impeded by mere eye-candy.)

**Comment by jpetrie** [comment]
It seems rather easy to expose this to `defaults` or even just as a box in the preference panel if it's really just changing that scalar in four spots. I will investigate.

**Comment by jpetrie** [comment]
I'd appreciate it if either or both of you could yank and build that PR and let me know if you run into anything other than the flicker at low time values (fixing that is probably more work than I can invest right now, I think it's due to all the window sleight of hand MacVim's going through).

**Comment by chdiza** [comment]
I tested it, and it seems to work fine.  I tested it at values of 0.0 and 1.0.

That "flicker"-like stuff is IIRC, as you say, due to all the sleight of hand.  I seem to recall people asking about this on the list years ago, and that Bjorn said nothing could be done.  I've been used to it for many  years now, so it isn't a big deal.  And there are other flickers in MacVim land that are far more worthy of effort!

**Comment by jpetrie** [comment]
Changes got merged in; I'll close this.

**Comment by chdiza** [comment]
@jpetrie This was a nice change, thanks!

**Comment by jordwalke** [comment]
Thanks!

**Comment by ychin** [comment]
The fade time is no more… See #1171 which removed it. To be precise, it now defaults to 0, where MacVim will just not do the fade. The previous flickering were mostly due to poor interactions with resizing / renderer, and those should have been all fixed with stateful renderer and so on. You can still set it back to 0.25 to get the old behavior back but I personally doubt people miss it.
