### ISSUE TITLE
Finder tags removed from files when saved

### ISSUE THREAD

**Issue by sloanlance** [macvim-dev/macvim#315]
Using MacVim (Custom Version 7.4 (81)), I opened a file that had a Finder tag assigned to it.  After I used MacVim to change the file contents, when I saved the file, the Finder tag was removed.  Adding the tag back in Finder, then altering the file with MacVim again achieved the same results.

I quit and restarted MacVim, but it still had the same effect.  Other editor applications didn't have this effect on the file tags.

**Comment by chdiza** [comment]
Try putting `set backupcopy=yes` in your `~/.vimrc` and see if that helps.

**Comment by jpetrie** [comment]
Without `backupcopy` enabled, vim will preserve "special attributes" by making a copy of the file; this includes the metadata for tags in the Finder. If `backupcopy` is set to "no," vim just writes a new file itself, and can't preserve any metadata it doesn't itself understand.

Setting `backupcopy` to "yes" should solve the problem for you. "auto" (the default) *should* also work. 

MacVim does not implement any of this behavior itself, it's all handled by vim; if you think there's a bug there you probably report it upstream.

**Comment by chdiza** [comment]
"auto" does not work, at least in my experience, at least not for preserving a file's "creation date".  I've had `&backupcopy` set to yes for years because of this.

I've been thinking that this should probably go in MacVim's `$VIM/vimrc`.  I hate the thought of adding to that file, which probably shouldn't exist in the first place.  But given that it does, `set bkc=yes` is a Mac-specific setting that preserves what Mac users have been used to for decades (way before there were Finder tags), namely "creation date".

**Comment by chdiza** [comment]
On second thought, I think it should just go in the FAQ or wiki.

**Comment by sloanlance** [comment]
I'll give that a try. Will `backupcopy` create those annoying files with a tilde appended to their names?

**Comment by chdiza** [comment]
> I'll give that a try. Will backupcopy create those annoying files with a tilde appended to their names?

Not unless you also have `set backup` in your vimrc.  See `:help backup-table`.
