### ISSUE TITLE
window flashing

### ISSUE THREAD

**Issue by zhaodawei** [macvim-dev/macvim#32]
Do you have found, use the mouse to adjust the window size, window flashing.why?
MacBook Pro (Retina, 15-inch, Late 2013) OSX 10.10.3 (14D136)
![flash](https://cloud.githubusercontent.com/assets/3748452/7609423/6289f0c0-f9a5-11e4-8562-a99c3a4f55a3.jpg)

**Comment by jpetrie** [comment]
I've been looking into this.

It happens only at certain window sizes, and appears like it might be related to the "lazy" resizing done during a live resize. In particular the flash tends to happen because the underlying view transitions through non-column multiples of a width even though it never visually appears to do so normally, and at certain widths the rendering is scrambled. The appearance is consistent with an incorrect stride on a bitmap, which suggests mishandling of some Cocoa rendering somewhere.

It only happens when resizing horizontally as far as I've seen. The problem is somewhere in the Core Text renderer; if you disable the Core Text renderer in MacVim's preferences window, the problem appears to go away.

Disabling columwise resize stepping makes the problem a lot easier to reproduce and more importantly allows you to hold the screen in that position indefinitely, which is useful for debugging.

**Comment by tobireif** [comment]
On my MacBook, MacVim shows flickering streaks during resize:

http://tobireif.com/non_site_stuff/for_macvim_bug_report_flickering/mac_vim_on_mac_os_10_10_resizing.mov

It does not occur in other apps I use.

**Comment by amadeus** [comment]
Just to add to this - here's a link to a vid showing more of this effect:

https://dl.dropboxusercontent.com/s/eq1ypgbs691rpb3/screencast_2016-02-12_12-50-19.mp4?dl=0

It would be really nice to get this fixed

**Comment by jordwalke** [comment]
Just executing `winsize` commands does not seem to cause flicker, yet when dragging the flickering is terrible. What if dragging just executed the corresponding `winsize` commands as you dragged?

**Comment by jordwalke** [comment]
@jpetrie / @splhack 
I know that @jpetrie mentioned rewriting the renderer (which might enable cool pixel granular scrolling), but to solve this glitching issue, might the `winsize` trick I suggested above be easy to implement? Would you be so kind as to estimate how difficult this is or how much time it might take?

**Comment by geoelectric** [comment]
Since #453 got duped to here, wanted to draw attention to the gif @ericvaladas posted in that thread demonstrating flashing with the default black on white. The flickering is *much* more apparent if you're on a light background.

**Comment by tobireif** [comment]
I don't get any flickering anymore.
