### ISSUE TITLE
Cannot repeat paste done in insert mode

### ISSUE THREAD

**Issue by DelvarWorld** [macvim-dev/macvim#33]
`vim -u NONE` load vim with no plugins
`i` go into insert mode
`⌘v` paste clipboard contents
`Esc` return to normal mode
`.` repeat the paste
Beep! The cursor moves back one character, which is a nice feature.

Repeating works fine if it comes from a register. Eg, replace `⌘v` above with `ctrl-r*`

Here's a workaround, which I figured out after a only 6 years of using MacVim:

    inoremenu Edit.Paste <C-r><C-p>*

but i'm not sure if that's the exact behavior of MacVim's `Edit.Paste`. It works better than Vim's default `ctrl-r *` which comes with a random number generator and a few config flags to determine indenting.

**Comment by jpetrie** [comment]
This is probably because ⌘V just calls paste#Paste() (defined in the vim runtime, under autoload). The function executes `"+gP` to paste text, but then executes `normal! i`, at which point `.` will repeat that "last change" of entering insert mode and doing nothing.

Is this really a MacVim-specific bug? Seems like this would happen in gvim on Windows as well, since paste.vim is part of the standard vim distribution.

**Comment by jpetrie** [comment]
This should be reported against [Vim itself](https://github.com/vim/vim), since that's where the runtime file in question comes from and MacVim isn't modifying it.
