### ISSUE TITLE
Pasted line from clipboard will inserted above current line in GUI.

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#367]
Pasted line from clipboard will be above current line in GUI and it will be inserted to current cursor position in terminal `/Applications/MacVim.app/Contents/MacOS/Vim` with same settings, same build, etc.

Can I control it somehow or at least have same experience as in `Vim`?

**Comment by adudek16** [comment]
I have this issue too. 
Any suggestions?

**Comment by ychin** [comment]
@eirnym  Can you elaborate? What command are you using?

If you are using Cmd-V, that's using the Edit -> Paste menu item, which is implement as `"+gP`, which is why is pastes before, not after. This is the same as core Vim. `"+p` still works for pasting clipboard content after the cursor and you can map whatever key you want to that as well.

**Comment by ychin** [comment]
Sorry, but I will have to say no and close this issue.

The main reason is that this is the default Edit → Paste action in Vim and I don't want to deviate from vanilla Vim as consistency across platforms is more important.

Also, the "before or after" question in normal mode is a constant one new Vim users have to learn and  figure out to become fluent in Vim. Just mapping Cmd-V to `p` instead of `P` isn't going to fix that. For example, if you want to paste something to the first column you have to do `"+P`, but if you want to paste something to the end you have to do `"+p`, unless you have `set virtualedit=onemore` where you can position the normal mode cursor one past the end. The point I'm trying to get across is that the way Vim normal mode interacts with insertion of text ('p' vs 'P', 'a' vs 'i') is something users just have to learn because cursors lie *on* characters, not *between* characters. You have to pick one (before or after). Note that this isn't an issue in insert mode.

**Comment by adudek16** [comment]
Is this behavior consistent between Windows, Linux, and OSX with the modification of using cmd vs ctrl + p?

**Comment by ychin** [comment]
As I said, Cmd-V is a shortcut for the Edit → Paste menu item, which is defined as `"+P`. Look up `menu.vim` in Vim for the definition. Cmd-V itself is a MacVim-specific shortcut as Cmd keys obviously work differently in other platforms, but Edit → Paste is generic.

**Comment by eirnym** [comment]
Thank you for an explanation, this is enough for me.
