### ISSUE TITLE
Crash when you do "set gfn=*"

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#37]
On  10.10.3, the command `:set guifont=*` crashes MacVim instantly.

This should bring up a font selection box.  It used to work all the way up through at least Mavericks.

Console.app shows the following (I had to insert some hard line breaks):
```
May 27 11:22:39 diza MacVim[362]: Layout still needs update after calling -[NSScrollView layout].
NSScrollView or one of its superclasses may have overridden -layout without calling super.
Or, something may have dirtied layout in the middle of updating it.  Both are programming
errors in Cocoa Autolayout.  The former is pretty likely to arise if some pre-Cocoa 
Autolayout class had a method called layout, but it should be fixed.

May 27 11:25:22 diza kernel[0]: Sandbox: MacVim(83196) System Policy: deny file-write-unlink
/Users/chdiza/Library/Saved Application State/org.vim.MacVim.savedState/restorecount.plist
```

**Comment by jpetrie** [comment]
I can't reproduce this (snapshot 76); do you have the rest of the crash from Console.app handy?

**Comment by chdiza** [comment]
(a) The rest?  There's more?

(b) If I do `mvim -u NONE -U NONE -N`, followed by `set gfn=*`, there is no crash, and the font dialog appears, BUT.... the same message about "Layout still needs update after..." is printed to the Terminal.

**Comment by chdiza** [comment]
I build from the repo, and I built the most recent commit.

**Comment by jpetrie** [comment]
If it's an actual crash (as it sounds like), there should be an entry under "User Diagnostic Reports" in the left panel of Console.app (use the "Show Log Lists" button on the toolbar if there is no left panel). There will be an entry like "MacVim_<timestamp>_<hostname>.crash" with, among other things, a stack backtrace under the header "Thread 0 Crashed:"

If it's not there I suppose it's possible some OS-level settings can prevent the storage of these reports. :(

My understanding of that message is that it basically shouldn't apply to anything that I know MacVim to be doing (using Auto Layout somewhere and not calling `[super layout]` from an override of `layout` in a subclass). A quick poke through the source shows MacVim isn't explicitly doing anything with NSScrollView subclasses that I can see, and I'd be surprised if it's using Auto Layout anywhere (since as far I recall, Auto Layout is the new hot thing). I suspect the message is being generated by calls the Font Manager itself makes.

(I can't reproduce the message yet, nor the crash, even with `-u NONE -U NONE -N` and windowing, native fullscreen, and custom fullscreen mode).

**Comment by chdiza** [comment]
There is no crash report.  Perhaps it's not technically a "crash".

> Can you get the stack trace by running your local build under a debugger?

I'm sorry, I don't know what that means.  I'm not a programmer.

> I'll try pulling that in tomorrow and seeing if I can reproduce with that

I get the pseudo-crash without the recent fullscreen fix.

**Comment by jpetrie** [comment]
Ah, I didn't realize. 

So, most of the likely code exists in the actual vim backend here (which I'm not really great at debugging). I did an experiment and forced the vim process to terminate and *that* will cause MacVim to quietly close without actually logging a crash report (so instead of looking for a crash for "MacVim" you might try looking for "Vim"). My theory now is that it's the backend vim process that crashes, and MacVim just decides to quit.

`:set guifont=*` should be functionally identical to `:macaction orderFrontFontPanel:`. That in turn is also mapped to the "Edit > Font > Show Fonts" menu item. So far I don't see any obvious code that might cause vim to crash here... but there's a lot of ugly pointer passing going on. I'd be curious to know:

- if `:macaction orderFrontFontPanel:` has the same effect for you,
- if showing the panel from the "Show Fonts" menu has the same effect for you,
- and if you're up for it, if you can bisect your vimrc and/or gvimrc to narrow down which options then cause `:set guifont=*` to crash (or if you can otherwise make your RC files accessible and I'll try running with them).

**Comment by chdiza** [comment]
> (so instead of looking for a crash for "MacVim" you might try looking for "Vim")

No crash report for Vim either.

I'm finding that I suddenly can't reproduce this.  This has become a thing with MacVim; there are other pseudo-crashes that are only sometimes reproducible.  Some simple action (like the &gfn mentioned here) will bring down MacVim (even with `mvim -u/U NONE`) on demand for a few days, leaving no actual crash report, and then suddenly stop doing it.  This happens on multiple machines and multiple OSes (Yosemite and Mavericks).

**Comment by chdiza** [comment]
This will start being reproducible again any flippin' minute.

**Comment by chdiza** [comment]
I get this on more than one machine, FWIW.

**Comment by splhack** [comment]
It is still happening?

**Comment by chdiza** [comment]
It still happens on  Yosemite.  I have not yet seen it on El Cap, but I haven't been trying very often.

**Comment by splhack** [comment]
I can't reproduce it. cloud you investigate it by yourself?

**Comment by splhack** [comment]
it seems no other crash reports. close.
