### ISSUE TITLE
Inconsistent behaviour in Spotlight 

### ISSUE THREAD

**Issue by longkai** [macvim-dev/macvim#399]
My macvim version is (8.0 patch 1-39) and runs on macOS 12.12.1. I found an inconsistent behaviour when working with Spotlight.

When I open a file in iTerm, it opens a new window(one icon in dock) of macvim and it's right. However, after I go to other applications then typing macvim in spotlight, it opens another new window, or process(two icons in dock) which is not I want.

I tried switching different preferences in the general tab, it doesn't work. What I want is only one process(one icon in dock) so I can go back from other application in Spotlight which most application does.

Feel free to correct me if I was wrong.

**Comment by chew-z** [comment]
It is tricky to grasp initially but  there are different ways to run MacVim and they never meet.

You can run mvim script (this is how you probably started MacVim from iTerm) or you could run the application `open -a "MacVim` (this is how Spotlight started MacVim). They are two separate instances. (and there is more)

The reason is that mvim script that comes with MacVim is far from perfect and it is so cause there are too many possible scenarios and the script keeps it simple. 

So you could google - some people improve mvim script for their use scenarios. Like [this](https://langui.sh/2009/10/01/improving-mvim-for-macvim/) or [this](https://github.com/susam/vimer) or [this](https://gist.github.com/shakefu/3780676).

**Comment by longkai** [comment]
It works. Thank you for your detailed info.

Robert J. <notifications@github.com>于2016年11月13日周日 下午4:07写道：
