### ISSUE TITLE
Where is the mvim script?

### ISSUE THREAD

**Issue by nkanellopoulos** [macvim-dev/macvim#475]
I am searching for the mvim script, to start MacVim from the terminal, as it is stated in the FAQ.

`$ find /Applications/MacVim.app -name "mvim"`
finds nothing.

Is the FAQ stale or am I missing something?

(Note: there is a MacVim executable in the bundle, but what I am looking for is being able to send a file to my running MacVim instance, from the terminal. Directly executing MacVim, added a second MacVim instance in the Dock. Which I find strange)

**Comment by nkanellopoulos** [comment]
Well, this is easy to miss. Why not include it inside the MacVim.app too?

<img width="650" alt="macvim_and_releases_ _macvim-dev_macvim" src="https://cloud.githubusercontent.com/assets/1705451/24036882/4b976bb4-0b04-11e7-8757-fe38faf4aed3.png">

**Comment by jpetrie** [comment]
I'm confused. Are you saying that the FAQ says to locate `mvim` by running that `find` invocation? Because [the FAQ here](https://github.com/macvim-dev/macvim/wiki/FAQ) doesn't, so you may be reading an old or unofficial FAQ.

If, on the other hand, you read the FAQ's statement that `mvim` "comes bundled with the MacVim download" to literally mean `mvim` was _in the application bundle_, I suppose I can see how that overload of the word "bundle" could be misleading. I've updated the wording to remove the specific use of the term "bundle."

**Comment by nkanellopoulos** [comment]
No, the FAQ does not state I should use `find` to find mvim :)
It says that one should use `mvim` to open files from the terminal.
But I could not find mvim, so I searched for it in the app bundle using find, to be sure I did not miss it.

**Comment by splhack** [comment]
- I put `mvim` script into the bundle, like `/Applications/MacVim.app/Contents/MacOS/mvim`.
- Updated the FAQ
