### ISSUE TITLE
Can I set vertical to "middle"?

### ISSUE THREAD

**Issue by AnnatarHe** [macvim-dev/macvim#493]
I set this in my .gvimrc:
```vim
set linespace=14
```
but got this
![image](https://cloud.githubusercontent.com/assets/8704175/24798933/402978a8-1bcb-11e7-9685-e192642f4f38.png)

I really except It can be in middle like this(Gvim in Ubuntu):
![image](https://cloud.githubusercontent.com/assets/8704175/24798972/6595b46c-1bcb-11e7-93e4-76b80cfac804.png)

So anybody can resolve this?

**Comment by jpetrie** [comment]
The point of `linespace` is to control how many pixels worth of vertical space appears between lines in the GUI. The intent, in core vim, of this feature is for when "the font uses the full character cell height, making lines touch each other," and also for when there's _too much_ space between lines in a font due to ascenders or descenders. 

The point of `linespace` is _not_ to middle-align text vertically for status bar widgets. What you're proposing here would break a useful compatibility feature for the sake of a prettified UI.

**Comment by AnnatarHe** [comment]
@jpetrie Can Macvim make an attribute to control the vertical style?
I have to say the UI is so ugly. I believe that many people have the same feelings as me.
(I even gave up mac because of this.😑)

**Comment by jpetrie** [comment]
Personally, I wouldn't want to.

We generally try to avoid MacVim-specific features like that, as they are harder to keep in sync with both core vim and across MacVim's two renderers. After taking a brief look at how `linespace` is handled in MacVim it might not be a simple change, as it sounds (from the current comments) like the current approach was done to vastly simplify things.

If somebody implemented the feature as a preference option or a `defaults` option, we'd consider integrating it.
