### ISSUE TITLE
Please bring back lua support

### ISSUE THREAD

**Issue by yacoob** [macvim-dev/macvim#50]
I'd like to use neocomplete with macvim. Sadly, it requires lua. Is there a solid reason why lua support is disabled in recent macvim builds?

**Comment by yacoob** [comment]
It'd be nice to get an official statement, whether it's something that's hard to do and requires some help, or is it just not going to happen because of some reason.

**Comment by douglasdrumond** [comment]
Sorry, if I recall correctly, MacVim never had Lua support, so it's not
exactly bring back. The problem is which version of Lua to use, there's no
default Lua in OS X. For Ruby and Python, MacVim is always complied against
system version (bad things do happen if you compile against other version
and someone tries to use it without that specific version, I know because
once I forgot RVM enabled and compiled with wrong Ruby).

2015年7月8日(水) 19:11 Jakub Turski <notifications@github.com>:

> It'd be nice to get an official statement, whether it's something that's
> hard to do and requires some help, or is it just not going to happen
> because of some reason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/macvim-dev/macvim/issues/50#issuecomment-119746310>.
>
-- 

Douglas Drumond

Androidから送信。

**Comment by yacoob** [comment]
I see - this does make sense. I don't think the Lua support is worth the trouble of including a lua interpreter or something like that. Thanks for the explanation.

**Comment by JakobR** [comment]
You could install macvim via [homebrew](https://github.com/Homebrew/homebrew), there's an option to enable lua support:

```
brew install macvim --with-lua
```

(Run `brew info macvim` to see a list of options.)

**Comment by yacoob** [comment]
I know I can do it - I explicitly wanted to avoid this, as you need whole XCode for this, and the resulting application is linked dynamically - which makes it bit brittle if you want to deploy it across different OSX versions for example.

But in the meantime I've simply dropped the neocomplete in favour of ycm.
