### ISSUE TITLE
Doing a search in MacVim changes the search string in Chrome ❗️

### ISSUE THREAD

**Issue by tobireif** [macvim-dev/macvim#501]
Doing a search in MacVim changes the search string in Chrome.

Steps:
In Chrome do cmd-f "foo"
In MacVim do / "bar" enter
Now in Chrome the search string is "bar".

This bug is very surprising and severe.

**Comment by chdiza** [comment]
It's been like this since 2008, and I'm not 100% sure it's a bug (I think it might be the cost of having searching in MacVim behave in a macOS-ish way; either that or some people---way back when---actually wanted it this way).

But it *is* 100% unbelievably beyond-the-pale annoying and I wish there were a way to switch it off, even if it it means recompiling with different flags.

**Comment by tobireif** [comment]
If the reason is "having searching in MacVim behave in a macOS-ish way" then I say I do want to get and use Vim's search behaviour when I search inside a file/buffer I had opened/created using MacVim - not a different behaviour.

I really hope this will be fixed. It's very bad to, as a side-effect, change data that has been entered in a completely separate app.

> But it is 100% unbelievably beyond-the-pale annoying 

Yes!

**Comment by jpetrie** [comment]
This is definitely an OS feature (although I wouldn't rule out the possibility that MacVim hand implemented it once-upon-a-time to mimic the OS feature before the OS made the APIs more accessible). We could potentially disable this, but it would need to be a `defaults` setting, since some people do like this behavior.

**Comment by jpetrie** [comment]
We use the `NSFindPBoard` in [a couple of places](https://github.com/macvim-dev/macvim/search?utf8=%E2%9C%93&q=NSFindPboard&type=). I'd wager this is probably related.

**Comment by splhack** [comment]
Maybe it would be better to only share the find pasteboard if user used Find dialog on GUI, but it would need to modify Vim code as well. It's not worth it. I'll add defaults way.

**Comment by tobireif** [comment]
Thanks!
