### ISSUE TITLE
Some emoji/unicode characters not rendered at proper widths

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#572]
Theres a good number of emoji and unicode characters that get cut off when rendered in Macvim, I've attached a file with a a ton of characters, and in there you can easily find the broken ones.

Is there any way this can be easily fixed? Or is it something that has to be handled on a character per character basis?

[characters.txt](https://github.com/macvim-dev/macvim/files/1420494/characters.txt)

**Comment by WillEccles** [comment]
I believe the issue is that the unicode characters are wider than the font you are using, and therefore (even though they many are rendered as double-width characters) the characters hang outside of the column. I doubt there is much you can do about it other than not use these characters.

**Comment by amadeus** [comment]
This used to be a problem with all emoji, and they did some stuff to make those characters double wide. I am pretty sure it's fixable, they just may have to add some additional characters to it.

I.E. ![example](http://wtf.amadeus.wtf/monosnap/_2017-10-30_13-52-31.png)

**Comment by WillEccles** [comment]
Ah, never knew they fixed the old ones. That's on the devs, then. Apologies for the misconception.

**Comment by eirnym** [comment]
⚙️ is an another good example of wide emoji, but even trufae/Therm is renders it wrong.

it's drown as a half if Core renderer is enabled or have a wrong width otherwise.

**Comment by eirnym** [comment]
My personal opinion is to low the priority of this issue as nobody has a good solution for this if we're speaking about monospaced font apps.

**Comment by Splarv** [comment]
I think this is duplicate #382.

Btw in common vim in the iTerm fine.

**Comment by ychin** [comment]
Not 100% sure if it's a dup but I will keep this open for now. It still needs to be fixed.

**Comment by Splarv** [comment]
> Not 100% sure if it's a dup but I will keep this open for now. It still needs to be fixed.
Not sure. iTerm with Vim and MacVim both designed to work only with **fixed** or **monospaced** fonts (fonts with fixed width of symbols). That the **fixed** font has symbols (emoji) which is wider, than other symbols is a problem of the font, not iTerm or MacVim. iTerm and MacVim behave differently with such buggy **fixed** fonts, iTerm mix symbols, but MacVim cut them. What is more 
correct is a question, obviously such behaviour determined by an underground GUI library. In any case enough just document that the font must be **fixed** or *monospace** (this is synonymous), and this bug is of font, but not of MacVim.

**Comment by ychin** [comment]
I believe this issue has been fixed when stateful renderer went in.
