### ISSUE TITLE
E254: Cannot allocate color 7

### ISSUE THREAD

**Issue by aliev** [macvim-dev/macvim#576]
When I'm trying to run :term command I see this error message:

```
E254: Cannot allocate color 7
```

My .vimrc is empty

For terminal vim is all good.

** UPD ** sorry the problem was with my terminal configuration, I removed base16-shell color theme (https://github.com/chriskempson/base16-shell), now all good :)

**Comment by llimllib** [comment]
FWIW, instead of removing base16-shell, I set it not to be loaded only when bashrc is run from inside vim:

```
# if we allow Base16 to run in macvim, it causes an infinite error loop
[ -n "$PS1" ] && \
  [ -z $VIM ] && \
  [ -s $BASE16_SHELL/profile_helper.sh ] && \
  eval "$($BASE16_SHELL/profile_helper.sh)"
```

I think this might honestly be considered a macvim bug? But I have a workaround so it doesn't bug me too much.

**Comment by fturcheti** [comment]
I had the same issue, but the workaround @llimllib suggested fixed it for me too.

**Comment by KarboniteKream** [comment]
I had the same issue, but I found out that if I launch MacVim normally (not `mvim`), `$TERM` is not set. In this 

I had the same issue. If I run MacVim normally (not with `mvim`), `$TERM` is not set, and this error occurs. But, if I run with `mvim`, it's set to `TERM=xterm-256color, the issue is resolved.

**Comment by ychin** [comment]
See my [comment](https://github.com/macvim-dev/macvim/issues/879#issuecomment-474699172) here about setting `TERM` in GUI vs terminal.

**Comment by KarboniteKream** [comment]
I tried the example you provided, but I still get the error about allocating the color.

**Comment by eirnym** [comment]
I use `zsh` with using 256 color palete for PS1. Running zsh as `!zsh -l' produces ESC characters printed directly as `[` and I see output below (it's totally not an issue for me). If I run within `:term` command with $TERM set, I see all colors and no issues with any key bindings I set.

![Zrzut ekranu 2019-04-5 o 10 26 04](https://user-images.githubusercontent.com/485399/55614445-3b652380-578d-11e9-9ea8-2e189d2dd3d7.png)

**Comment by ychin** [comment]
@KarboniteKream Are you using base16-shell too? Have you tried @llimllib's workaround? There seems to be a few things going on here so I would like to address and understand them one by one. Is base16-shell just a coloring utility for terminal? I would like to see if it causes problems on Linux's gVim as well to help isolate issues since I suspect this is a Vim bug (?).

**Comment by KarboniteKream** [comment]
Yes, I'm also using `base16-shell`. @llimllib's workaround works fine. `base16-shell` basically just modifies some terminal colors, so the same colorscheme works in terminal Vim.

I can setup a Linux VM to help test on gVim.

**Comment by ychin** [comment]
I reproduced the same issue on Linux with a fresh installation of base16-shell and GVim. I suspect this is a bad interaction with how the script works and the GUI’s color handing code.

Please file an issue with base16-shell (and maybe Vim) directly as I don’t think this is MacVim specific. They will be able to provide better contexts than here. This issue is also already closed so I won’t reopen.
