### ISSUE TITLE
Python 2.7.6 can't import "string" library, nor many others

### ISSUE THREAD

**Issue by evoling** [macvim-dev/macvim#63]
According to `:python import sys; print sys.version` I have python 2.7.6, but when I try `:python import string` I get an ImportError. `python print sys.path` shows a strangely minimal-looking list:

```python
['/Users/USER/Library/Python/2.7/lib/python/site-packages', 
'/usr/local/lib/python2.7/site-packages', 
'/Library/Python/2.7/site-packages', 
'_vim_path_', 
'/Users/USER/.vim/bundle/riv.vim/autoload/riv/']
```

Spot testing shows that I *can* import e.g `sys`, `os`, `re`, but I *can't* import e.g. `math`, `StringIO`, `textwrap`, `codecs`. I'm [not the only one](http://stackoverflow.com/questions/24212957/stringio-and-string-import-error-on-installing-vim-latex-via-pathogen) having this problem.

I am running Snapshot 77 on Yosemite, installed via homebrew.

**Comment by eirnym** [comment]
I can say nothing about building MacVim from HomeBrew, but I use MacVim from MacPorts only because I really need Python3 support. Are there any packages you need to be installed to python to use riv.vim? Which bundle manager do you use?

`: python import string; print string.digits` works well on official MacVim snapshot release or MacPorts with Yosemite. I use `pathogen` and `python-mode`/`syntastic`/etc works well.

I'll build and test MacVim from `MacPorts` with El Capitan a bit later.

**Comment by eirnym** [comment]
Vim form MacPorts works on El Capitan as well.

@evoling please, check your environment, build environment, `vimrc`. May be you have broken HomeBrew.

**Comment by evoling** [comment]
Thanks for checking this out. I've tried the same thing (with the same .vimrc/.vim) on my computer at home and it works fine -- the obvious difference is that `sys.path` has lots of directories in it, including all the ones under `/System/Library/Frameworks/Python.framework/`.

Anyway, it doesn't look like this is anything to do with MacVim. Sorry for the bother.

**Comment by splhack** [comment]
Could you try Snapshot 80 binary? https://github.com/macvim-dev/macvim/releases/tag/snapshot-80 It works fine with Python 2.7.
If you still want to build MacVim by yourself using Homebrew, and the issue still happens, could you ask the author of Homebrew MacVim formula about the issue?
