### ISSUE TITLE
MacVim doesn't hide menu bar in secondary display when using pre-Lion fullscreen 

### ISSUE THREAD

**Issue by douglasdrumz** [macvim-dev/macvim#7]
For description, see this comment.
https://github.com/macvim-dev/macvim/commit/b517b310559bb4c8d297f9b2dec6aa972446b504#commitcomment-10915316

**Comment by chdiza** [comment]
This is separate from the white flash issue.

I'm going to bisect later to find out where this non-hiding appeared.

**Comment by splhack** [comment]
It is still happening? and I believe you @chdiza are the only person who uses MacVim on OS X 10.4, 10.5, 10.6, and 10.7. So, could you fix the issue?

**Comment by chdiza** [comment]
This issue is not in any way about old versions of OS X.  It is about one of the two styles of "fullscreen behavior" we support, both of which work and are meant to work on 10.7 and up.  (One of them doesn't and can't work on 10.6 or under.)  Indeed, my original report of this issue is of incorrect behavior on Yosemite.  The label "Deprecated OSX" is not right, so I'm going to remove it.

As to whether this behavior is still happening, I can't test this right now since I am not at a desk with an external monitor.

**Comment by splhack** [comment]
how about 10.11? and what is the result of the bisect?

**Comment by splhack** [comment]
Anyway we don't need MMFullScreenWindow for 10.10 or later. We should make MMFullScreenWindow deprecated.

**Comment by chdiza** [comment]
>Anyway we don't need MMFullScreenWindow for 10.10 or later. We should make MMFullScreenWindow deprecated.

No, no, no, a thousand times no :smile:.  The older style of fullscreen is preferable to the Lion-and-up style in many ways, depending on one's workflow, and not just aesthetically.  My workflow depends on its existence.

It is a giant pain in the butt to wait for the Mac's animation delay when switching into Lion-and-up mode.  Also, that forces the newly-fullscreened window onto a different space than it used to be on, which is annoying enough even if it didn't carry an annoying animation delay with it.  Also, it prevents there being two fully-fullscreened windows on the same space.  Also, it prevents there being a fullscreened window and and non-fullscreened window on the same space.  All of these things that the Lion-and-up mode prevents are sometimes useful.

There is just no reason to drop it.  It's not hurting anything, and it helps some people.

In fact, the original fullscreen style is almost the entire reason I use MacVim rather than just vim in the console like I used to years ago.

I know some people like the Lion-and-up style too.  That's fine.  We can have both without problems.

**Comment by splhack** [comment]
Then, what is the result of the bisect?

**Comment by chdiza** [comment]
> Then, what is the result of the bisect?

I will do the bisect when I am sitting at a place that has an external monitor I can use for testing.

**Comment by cristibalan** [comment]
I use both MacVim and iTerm2 with the non-native fullscreen option. Just got an external monitor today and hit this issue, then noticed that iTerm2 doesn't have it. 

Unfortunately, I can't write objc/Cocoa, but I grepped the sources a bit and found out something.

It seems that [iTerm2 sets the menubar to autohide](https://github.com/gnachman/iTerm2/blob/c38ef0f126711606fac6aa3c664b2f5d50aef81d/sources/PseudoTerminal.m#L5809) when entering fullscreen on all screens while [MacVim sets the size of the window](https://github.com/macvim-dev/macvim/blob/master/src/MacVim/MMFullScreenWindow.m#L375) to be less than the toolbar.

I have the following in my config:

```
function! OnVimEnter()
  if has("macunix") && has("gui_running")
    set antialias
    set fuoptions=maxvert,maxhorz
    set fullscreen
  endif
endfunction
autocmd VimEnter    * call OnVimEnter()
```

The behaviour I'm seeing is that when MacVim starts the MenuBar is fixed on top and covers part of the first row.

![macvim-fullscreen-auto](https://cloud.githubusercontent.com/assets/122/11093819/09befa60-8895-11e5-9f3c-7a9d7aebeab5.png)

If I then exit fullscreen and enter it again, the window positions itself under the menubar.

![macvim-fullscreen-manual](https://cloud.githubusercontent.com/assets/122/11093827/10fcc3ca-8895-11e5-93f5-550cb302fd73.png)

Hope this helps.

**Comment by hkdsun** [comment]
any updates on this issue? It would be nice to do what iTerm2 does. 

Like @chdiza said my workflow is having iTerm2 and MacVim overlay each other in older-style fullscreen mode and switch between them with a shortcut (or use transparent windows to see through the focused window)

**Comment by ychin** [comment]
Kind of better late than never, but this is finally fixed! So that's the update 😅.

Will be out in the next update (r170) along with a couple native/non-native fullscreen improvements.
