### ISSUE TITLE
Statusline (or command line) on the touchbar

### ISSUE THREAD

**Issue by vitaly-zdanevich** [macvim-dev/macvim#748]
Continue of https://github.com/macvim-dev/macvim/pull/715#issuecomment-422152518

![macvim-statusline](https://user-images.githubusercontent.com/3514015/45676423-56967b80-bb3a-11e8-9fdf-ff1384d367a3.jpg)

**Comment by alextes** [comment]
ooooh, will the touch bar finally get some neat use for me 😍 ?

**Comment by sajdre** [comment]
could you explain how to get this please, it's sooo neat!!!

**Comment by vitaly-zdanevich** [comment]
It was my Gimp art.

**Comment by ychin** [comment]
With the release of the M3 14" MacBook Pro, Apple has officially stopped making any new hardware that has a Touch Bar, with the M2 13" MacBook Pro being the last product that had it. Because of that, there will be no more effort put in for new Touch Bar features, sorry.

Meanwhile, 🪦🫗  Touch Bar. I personally liked it despite it being a little polarizing and seemed to never really catch on with other third-party apps (or even first-party Apple ones).
