### ISSUE TITLE
Command line on the touch bar

### ISSUE THREAD

**Issue by vitaly-zdanevich** [macvim-dev/macvim#750]
Related to https://github.com/macvim-dev/macvim/issues/748

**Comment by ychin** [comment]
With the release of the M3 14" MacBook Pro, Apple has officially stopped making any new hardware that has a Touch Bar, with the M2 13" MacBook Pro being the last product that had it. Because of that, there will be no more effort put in for new Touch Bar features, sorry.

Meanwhile, 🪦🫗  Touch Bar. I personally liked it despite it being a little polarizing and seemed to never really catch on with other third-party apps (or even first-party Apple ones).
