### ISSUE TITLE
Vim Ruby Version 2.3.7 but expected Version 2.5.3

### ISSUE THREAD

**Issue by kyletolle** [macvim-dev/macvim#798]
I have used MacVim for years and absolutely love it. Thanks in advance for the help here.

I was excited for the new release because it fixed #257, which I reported in the past. However, after upgrading to MacVim 8.1.560 (152), I'm unable to use command-t in MacVim, because the expected version of Ruby doesn't match.

I get the following error:
> Vim Ruby version: 2.3.7-p456
> Expected version: 2.5.3-p105
![vim ruby error](https://user-images.githubusercontent.com/260869/49548564-17173a00-f8b4-11e8-9de3-c453312d257f.png)

I've tried brew uninstalling macvim, setting `rbenv global 2.5.3`, and then brew installing macvim. This did not work.

I've seen #779 and tried setting `rubydll` like it recommends. In order to do so, I installed ruby through brew
```
brew install ruby
```
In order to get a `libruby.2.5.dylib`, which I've found in the following path:
```
/usr/local/Cellar/ruby/2.5.3_1/lib/libruby.2.5.dylib
```

And I set `rubydll` as follows at the top of my `.vimrc`:
```
set rubydll=/usr/local/Cellar/ruby/2.5.3_1/lib/libruby.2.5.dylib
```
But I keep getting the error that vim is using Ruby version 2.3.7.

Would you have any ideas as to why vim is not using Ruby version 2.5.3?

Here's some system information:
macOS: `10.14.1`
Homebrew: `1.8.4`
rbenv: `1.1.1`
rbenv ruby: `2.5.3`
system ruby: `2.3.7`
brew ruby: `2.5.3`

Thanks again for all your hard work!

**Comment by ychin** [comment]
It sounds more like Cmd-T is expecting 2.3.7 to me. Did you rebuild the C components? One issue with the Cmd-T plugin is that the native component + ruby does mean there's more fussing needed to get it to work.

You can always do `:ruby puts RUBY_VERSION` in Vim to be sure what Vim is using.

**Comment by kyletolle** [comment]
I was able to compile Command-T against Ruby 2.3.7 to get that Command-T working for me, since MacVim uses Ruby 2.3.7.

Still not certain why I couldn't get MacVim to use Ruby 2.5.3, though.

The release notes say:
```
Script interfaces have compatibility with these versions:
…
Ruby 2.5
```
And this lead me to believe that I would need to have Ruby 2.5 installed in order to use MacVim, but this does not seem to be the case. Is it mentioned anywhere what version of Ruby MacVim requires?

**Comment by ychin** [comment]
Cool! Glad to see if working for you.

I'm not sure why MacVim keeps using the 2.3 library. Setting `rubydll` should work and you can try setting it at runtime instead of in your vimrc to see if it works.

As for the versioning, Vim is usually compiled against a particular Ruby version, so when we build MacVim we do the same thing. Since we compile with `+ruby/dyn` we load the library dynamically so that users who don't care about Ruby don't have to deal with it. Technically, the library you load in *should* match the version Vim is compiled with. See `:h ruby-dynamic`:

> Unix ~
> 
> The 'rubydll' option can be used to specify the Ruby shared library file
instead of DYNAMIC_RUBY_DLL file what was specified at compile time.  The
version of the shared library must match the Ruby version Vim was compiled
with.

That said on my machine I find that it works whether I use a 2.3 or 2.5 library, so the changes may not be big enough.

**Comment by aeciolevy-ven** [comment]
I have spent some hours trying to match the version but without success...

```
cd ~/.vim/bundle/command-t/ruby/command-t/ 
rvm use 2.3.7
ruby extconf.rb
make clean 
make

```

I tried to do it on the and it did not work as well..
```
cd ~/.vim/bundle/command-t/ 
```
