### ISSUE TITLE
MacVim auto-updated while only checking is enabled

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#808]
This happened first time with release 152. Before it checked updates, but not updated. Please, fix it.

**Comment by ychin** [comment]
@eirnym Are you sure you didn't accidentally check the checkbox that says "Automatically download and install updates in the future"? There was no changes made to the updater (Sparkle) AFAIK.

You can check by typing `defaults read org.vim.MacVim SUAutomaticallyUpdate` in the terminal. If it does say `YES`, and you want to remove it, type `defaults delete org.vim.MacVim SUAutomaticallyUpdate` in the terminal.

**Comment by eirnym** [comment]
@ychin yes, I'm sure about this as I've never seen it and the previous update was a while ago. But I have this option set. 

Could you expose it to settings to make it controllable at any time?

**Comment by ychin** [comment]
I'll expose it so the user will see it in the preference pane. I agree it's annoying that there's no user-visible way to undo the "always downloading updates in the background automatically" checkbox that only shows up in the update dialog box. (Since that dialog box doesn't show up when auto-update is enabled).

**Comment by eirnym** [comment]
Thank you
