### ISSUE TITLE
Donations to support development

### ISSUE THREAD

**Issue by marcknock** [macvim-dev/macvim#814]
How do we donate to continue to support or fund development? Is there a Patreon or donate link somewhere?

**Comment by ychin** [comment]
Hi @marcknock, we appreciate the thought and I'm glad you like MacVim. Currently MacVim isn't really set up to receive donations or use the resources to hire developers, and I prefer keeping MacVim purely volunteer-based for now. As of now the most precious resource that we lack is time. If anyone want to contribute we always appreciate people looking through the issue list and submitting pull requests!

Since MacVim's core goal is to be a native port of Vim, I feel obligated to link to this: https://www.vim.org/sponsor/

Thanks.

**Comment by ychin** [comment]
There is now a sponsorship page set up! See announcement: https://github.com/macvim-dev/macvim/discussions/1271

**Comment by ernstki** [comment]
> There is now a sponsorship page set up! See announcement: #1271

👉 https://github.com/sponsors/macvim-dev
