### ISSUE TITLE
MacVim is lagging behind

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#824]
We're 38 patches behind vim now.  @ychin is doing great work, but I hope we aren't returning to the days before @splhack took over (when there were hardly any merge-ins from upstream).

The highest priority should be to have vim merged in quickly when they make a change (except of course when they do something that doesn't affect us like make a fix for Windows).  Things like tweaks to tab bars and applescript should take a backseat.   More major things like making sure the new rendering works well are important, but I don't think they should freeze out vim updates.

**Comment by ychin** [comment]
I'll need to merge it in tomorrow since there are some merge conflicts and I don't have time to resolve it now.

The last merge was 9 days ago so this is a fair criticism but I won't commit to any cadence higher than roughly weekly. Also, binary release is currently the primary way MacVim is released (which I plan to make ~monthly), so you should expect that to be the upper bound to how long it takes for a change from Vim master to get merged to MacVim.
