### ISSUE TITLE
“mvim” shifts focus to leftmost macvim window

### ISSUE THREAD

**Issue by FGasper** [macvim-dev/macvim#83]
Hello,

When I type “mvim” from the command line, MacVim assigns focus to the leftmost MacVim window that I have open.

This is pretty annoying and seems to be a recent regression; I don’t recall this on Snow Leopard when using the latest snapshot that was available for that OS.

**Comment by jpetrie** [comment]
What did it used to do (or rather what do you expect it to do)? Do you happen to remember what the last snapshot number was for the instances you saw it working the way you expect?

There was a change to `mvim` a little while ago, as far as I recall it just reordered the search priority for the application though. Beyond that it hasn't changed much since 2008. Which OS version are you on now?

**Comment by FGasper** [comment]
On 7 Oct 2015 12:54 PM, Josh Petrie wrote:
> What did it used to do (or rather what do you expect it to do)? Do you
> happen to remember what the last snapshot number was for the instances
> you saw it working the way you expect?

I would expect it to focus the newly-opened window. This is the behavior 
that I observe on my laptop.

I can’t remember which snapshot I was on … just that it was the last one 
made for Snow Leopard.

>
> There was a change to |mvim| a little while ago, as far as I recall it
> just reordered the search priority for the application though. Beyond
> that it hasn't changed much since 2008. Which OS version are you on now?

I’m using OS X Mavericks on a Mac Pro from about 5 years ago. There are 
three monitors, arranged side-by-side.

The laptop runs Yosemite, has no external monitors, and behaves correctly.

Both machines have MacVim installed via MacPorts.

Is there a “debug” mode that I could enable to see why it’s focusing the 
leftmost window on the Mavericks machine?

-FG

**Comment by jpetrie** [comment]
Well, nothing really for mvim, which is just a shell script. There's [this](https://github.com/macvim-dev/macvim/wiki/Debugging) you could enable for MacVim proper.

I feel like this behavior (which I can't reproduce on 10.11) is probably related to some notification the app is getting when opening the new window, since it seems unlikely to actually be in the `mvim` script itself.

**Comment by chdiza** [comment]
I can't reproduce this on 10.11, 10.10, 10.9, 10.5, or 10.4.

But then again, I don't install from MacPorts.

@FGasper would you mind pasting in the output of `defaults read -app MacVim`?  Also, does this behavior occur even if all your already-open MacVim windows are on the same monitor?

**Comment by FGasper** [comment]
@chdiza I get the following from that command:
```
Felipe@Felipes-Mac-Pro ~
> defaults read -app MacVim
2015-10-08 10:41:19.987 defaults[40782:507] Couldn't find an application named "MacVim"; defaults unchanged
```
Actually, now that I dig a bit more, it seems to be this:

- new window opens up on the screen where the last MacVim window was focused
- after opening new window, one of the MacVims on the opening Terminal window’s screen gets focused.

So, if you run “mvim” on a different screen than on which you last worked with MacVim, a disparity of focus/new-window can ensue … does that ring any bells?

**Comment by FGasper** [comment]
I tried unchecking “Displays have separate Spaces”, and that resolved the issue for me.

**Comment by chdiza** [comment]
> Couldn't find an application named "MacVim"; defaults unchanged

Now that is bizarre.  What about `defaults read org.vim.MacVim`?
