### ISSUE TITLE
who can help me fix it(home-brew install)

### ISSUE THREAD

**Issue by alextend** [macvim-dev/macvim#850]
$ brew cask reinstall macvim
==> Satisfying dependencies
==> Downloading https://github.com/macvim-dev/macvim/releases/download/snapshot-154/MacVim.dmg
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/8e71a09787b165e04435baa7cbf7cc836bafefd68f8c1b2db89151b2f028998b--MacVim.dmg
==> Verifying SHA-256 checksum for Cask 'macvim'.
Error: Cask 'macvim' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"

$ brew cask uninstall macvim
Error: Cask 'macvim' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"

**Comment by ychin** [comment]
I don't use Homebrew Cask so my knowledge here is limited but seems like the ":mountain_lion" dependency stuff has been removed in https://github.com/Homebrew/homebrew-cask/pull/57235. I'm not sure why you see that. Do you need to update your brew formulas so you pick up this change?

Otherwise file an issue at https://github.com/Homebrew/homebrew-cask/issues

**Comment by alextend** [comment]
> I don't use Homebrew Cask so my knowledge here is limited but seems like the ":mountain_lion" dependency stuff has been removed in [Homebrew/homebrew-cask#57235](https://github.com/Homebrew/homebrew-cask/pull/57235). I'm not sure why you see that. Do you need to update your brew formulas so you pick up this change?
> 
> Otherwise file an issue at https://github.com/Homebrew/homebrew-cask/issues

thx,it's OK,i remove a folder /usr/local/CaskRoom/macvim.

**Comment by ychin** [comment]
Ok. Can you close the issue then?
