### ISSUE TITLE
macvim doesn't load colorschemes with DOS line endings

### ISSUE THREAD

**Issue by DervishD** [macvim-dev/macvim#851]
macvim 8.1.873 with MacVim GUI

When loading a colorscheme containing DOS newlines, macvim doesn't show an error but doesn't load the colorscheme anyway.

If loaded by hand, from within macvim, errors are shown for the newlines, but only if loaded by hand.

I don't know the reason, and I prefer not to elaborate more just in case this is a known issue with a known workaround (I haven't found much information except [this](https://stackoverflow.com/a/4080736/4994781))

I can provide more information or perform additional tests, if needed. So far, I've fixed this problem by changing the newlines in my colorscheme from DOS to UNIX.

**Comment by ychin** [comment]
This is a general Vim problem, in that you need to use the file format specific to the OS for your vimrc to work (it doesn't do auto-conversion unlike editing a file). If you launch Vim or MacVim (using the `mvim` alias) from the terminal you will indeed see the correct error messages about the `^M` appearing in your vimrc. If you are launching MacVim directly then it won't report these error messages to the user similar to how gVim works.

If you are sharing your vimrc using Git you probably want to use Git's `core.autocrlf` to auto-convert the newline format for you. Otherwise you will need to make sure to convert the file yourself (just open the vimrc file, and do `set ff=unix` / `:w`).

**Comment by DervishD** [comment]
Thanks @ychin. I thought it was a macvim problem because I've been using the same set of config files (not sharing them using Git, but using Google Drive) in UNIX format in Windows and Ubuntu without any problem. And in UNIX format they work under Mac, too. The only one which was in DOS newlines format was the colorscheme and it has worked in a Debian machine, in Windows and only failed in Mac.

Anyway, it's easy to fix, I already converted the files.

**Comment by ychin** [comment]
Huh, not sure why it worked on the Debian Vim honestly. There may be some subtle difference there. Anyway, closing the issue since you have resolved the problem.
