### ISSUE TITLE
[Feature Request] option in General or Advanced settings  to hide titlebar

### ISSUE THREAD

**Issue by acidjazz** [macvim-dev/macvim#933]
Shot out to @splhack for #111 , would just be nice to be able to check a box in the MacVim options to hide the titlebar instead of having to run

```bash
$ defaults write org.vim.MacVim MMNoTitleBarWindow true
```

**Comment by eirnym** [comment]
Thank you for a feature request, @acidjazz 

I'd also prefer to have all options visible one way or another.

**Comment by mvcouwen** [comment]
I’d rather have an option to give the title bar a modern look similar to the ‘minimal’ look for iterm2. This look is based the appearance of Electron apps (https://www.iterm2.com/documentation-preferences-appearance.html). In my opinion this as useful as the titlebar but less distracting. Ofcourse having an option to completely remove the titlebar would already be a good first step.

**Comment by eirnym** [comment]
@mvcouwen Could you add some screenshots for your idea? Could you also check if it already implemented (`:help macvim`)?

**Comment by mvcouwen** [comment]
Sure!

See e.g. this screenshot
![this](https://images.ctfassets.net/ibq1vhkmncem/3vGKv92ZFY0cw8oe64mGAE/73a2a3fa7334608bc10743dbfdd61ba3/iterm2-final-setup.jpg?fm=jpg&fl=progressive&w=3840&h=2160&q=70&q=70)
from [here](https://www.felixjung.io/posts/pretty-iterm2-with-a-modern-titlebar/).

This feature does not seem to be implemented.

**Comment by eirnym** [comment]
Transparent titlebar is implemented. I agree, that tabs could be integrated to titlebar as well if a user wants.
Do you want to contribute implementation of them for MacVim?

**Comment by mvcouwen** [comment]
I would like to but I am afraid I don't know anything about the underlying code for macvim. Maybe I do in the future and then I might give it a try. That will not be anytime soon though.

**Comment by acidjazz** [comment]
Love the minimal look, but also no title at all! Can we do both? maybe a new feature request @mvcouwen ?

**Comment by eirnym** [comment]
@acidjazz no title at all is already implemented and documented `:help macvim`

**Comment by ychin** [comment]
In particular, do `:help MMTitlebarAppearsTransparent`.

I will be open to pull requests for a "modern style", although I'm a little weary of adding even more customization to window styles and tabs. Features are good but they add complexity and general maintainence cost, so I have to weigh how much value there is versus having to juggle multiple tabs implementation. Seems like iTerm has "Regular" (regular window with tabs below title), "Minimal" (big combined title / tabs bar), "Compact" (small regular size combined title / tabs bar). I think it's feasible to do something similar to "Compact" and just put the tab bar there, but there's a fair bit of code with assumptions of how the tabs work that I am not inclined to take that on now.

@mvcouwen I think you should probably make another issue instead of this one if you want that feature just to make it easier to have discussions specific to the feature.

**Comment by mvcouwen** [comment]
I have made another issue: #962.
