### ISSUE TITLE
MacVim snapshot 159 vim spell randomly flagging first word in lines

### ISSUE THREAD

**Issue by trondbn** [macvim-dev/macvim#971]
**Describe the bug**
MacVim snapshot 159 vim spell randomly marks a lot of words that appear first in their line as bad. First suggested correction seems to always be capitalizing the word, but after accepting this it is still marked as bad.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `mvim --clean`
2. Edit a text file, such as the one attached to this report.
3. Type ':set spell'
4. Red squiggly lines:
![Screenshot 2019-10-23 at 10 09 50](https://user-images.githubusercontent.com/28560585/67372066-9b7eb400-f57d-11e9-8367-a1ce31bf0135.png)

**Expected behavior**
Less squiggling: (taken with snapshot 157)
![Screenshot 2019-10-23 at 10 13 39](https://user-images.githubusercontent.com/28560585/67372307-fc0df100-f57d-11e9-880e-a5432ed59e55.png)

**Environment:**
 - Vim version:  8.1.2168
 - OS: macOS 10.15 Catalina (19A602)
 - Terminal: GUI

**Additional context**
Cleaning out `~/.vim/spell/` does not help

**Sample file**
[lorem_ipsum.txt](https://github.com/macvim-dev/macvim/files/3761026/lorem_ipsum.txt)

**Comment by ychin** [comment]
I think this is https://github.com/vim/vim/issues/5072 which was fixed in https://github.com/vim/vim/commit/7751d1d1a3d447d0d48f57f34e0da9f7c6ac433d (v8.1.2172). There should be an update soon to address app notarization issues which will come with this.

**Comment by chrisbra** [comment]
We had a recent discussion about this at [vi.stackexchange.com](https://vi.stackexchange.com/questions/21567/where-do-i-fix-partial-words-incorrectly-identified-as-errors-with-spell)

Copying here my answer from there:

This is a [known bug](https://github.com/vim/vim/issues/5078), introduced by patch [v8.1.2153](https://github.com/vim/vim/releases/tag/v8.1.2153) that has since been fixed with patch [v8.1.2172](https://github.com/vim/vim/commit/7751d1d1a3d447d0d48f57f34e0da9f7c6ac433d), so you'd need to update your MacVim to a new Version.

**Comment by eirnym** [comment]
@trondbn snapshot 160, please check it

**Comment by trondbn** [comment]
Confirmed fixed in snapshot 160.
